#!/usr/bin/env python3
"""Generate the capture-scoped VRage.Voxels.Native forwarding wrapper."""

import json
import re
from pathlib import Path


ROOT = Path(__file__).parent.parent
CAPTURES = Path.home() / "Documents/se2-native-wrappers/Playback/TestData/NativeCapture"
OUTPUT = ROOT / "src/Voxels.cpp"

TYPE_MAP = {
    "void": "void",
    "ptr": "void *",
    "fnptr": "void *",
    "i4": "int32_t",
    "i8": "int64_t",
    "u1": "uint8_t",
    "bool4": "int32_t",
}


def load_signatures():
    signatures = {}
    paths = sorted(CAPTURES.glob("*/VRage.Voxels.Native.jsonl"))
    if len(paths) != 3:
        raise SystemExit(f"expected 3 Voxels captures, found {len(paths)}")
    for path in paths:
        with path.open(encoding="utf-8") as stream:
            for line in stream:
                if '"ph":"sig"' not in line:
                    continue
                record = json.loads(line)
                signature = {"ret": record["ret"], "params": record["params"]}
                previous = signatures.setdefault(record["ep"], signature)
                if previous != signature:
                    raise SystemExit(f"conflicting signature for {record['ep']}")
    if len(signatures) != 33:
        raise SystemExit(f"expected 33 Voxels exports, found {len(signatures)}")
    signatures["VrSewGuide_InvalidateGenerated"] = {
        "ret": {"kind": "void"},
        "params": [
            {"kind": "ptr", "n": "instance"},
            {"kind": "struct", "type": "Vector3I", "size": 12, "n": "minRange"},
        ],
    }
    signatures["VrSewGuide_SetMesh"] = {
        "ret": {"kind": "void"},
        "params": [
            {"kind": "ptr", "n": "instance"},
            {"kind": "ptr", "n": "mesh"},
            {"kind": "ptr", "n": "dataCache"},
        ],
    }
    signatures["VrVoxelMesh_Clear"] = {
        "ret": {"kind": "void"},
        "params": [{"kind": "ptr", "n": "instance"}],
    }
    for name in signatures:
        if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", name):
            raise SystemExit(f"unsupported export name: {name}")
    return sorted(signatures.items())


def cpp_type(value):
    if value["kind"] == "struct":
        type_name = value.get("type", "").rsplit(".", 1)[-1]
        expected_size = {"Vector3I": 12, "AmbientOcclusionArgs": 28}.get(type_name)
        if expected_size != value.get("size"):
            raise SystemExit(f"unsupported struct ABI: {value}")
        return type_name
    try:
        return TYPE_MAP[value["kind"]]
    except KeyError:
        raise SystemExit(f"unsupported ABI kind: {value['kind']}") from None


def parameter_names(signature):
    names = []
    for index, param in enumerate(signature["params"]):
        name = re.sub(r"[^A-Za-z0-9_]", "_", param.get("n", f"arg{index}")).strip("_")
        names.append(name or f"arg{index}")
    return names


def emit(signatures):
    lines = [
        "// Generated by tools/generate_voxels_wrapper.py. Do not edit.",
        "#include <cstdint>",
        "#include <cstdlib>",
        "#include <mutex>",
        "#include <stdexcept>",
        "#include <string>",
        "",
        '#include "dll_loader.h"',
        "",
        "struct Vector3I {",
        "    int32_t x, y, z;",
        "};",
        "",
        "struct AmbientOcclusionArgs {",
        "    float values[7];",
        "};",
        "",
        "static_assert(sizeof(Vector3I) == 12);",
        "static_assert(sizeof(AmbientOcclusionArgs) == 28);",
        "",
        "namespace {",
        "pe_image voxels_image;",
        "std::once_flag voxels_once;",
        "std::string voxels_path;",
        "thread_local bool voxels_thread_ready;",
        "void *sysv_assertion_callback;",
        "",
        "void WINAPI assertion_bridge(const char *message)",
        "{",
        "    if (sysv_assertion_callback)",
        "        reinterpret_cast<void (*)(const char *)>(sysv_assertion_callback)(message);",
        "}",
        "",
        "void initialize(const char *dll_path, const char *sidecar_path);",
        "",
        "void ensure_thread_info()",
        "{",
        "    initialize(nullptr, nullptr);",
        "    if (voxels_thread_ready)",
        "        return;",
        "    if (!setup_nt_threadinfo(nullptr))",
        "        std::abort();",
        "    pe_ensure_tls_for_loaded_images();",
        "    voxels_thread_ready = true;",
        "}",
        "",
    ]

    for name, signature in signatures:
        ret = signature["ret"]
        pe_ret = "void" if ret["kind"] == "struct" else cpp_type(ret)
        params = []
        if ret["kind"] == "struct":
            params.append(f"{cpp_type(ret)} *")
        params.extend(f"{cpp_type(param)} *" if param["kind"] == "struct" else cpp_type(param)
                      for param in signature["params"])
        lines.append(f"using {name}_t = {pe_ret}(WINAPI *)({', '.join(params) or 'void'});")
        lines.append(f"{name}_t p{name};")

    lines += [
        "",
        "void initialize(const char *dll_path, const char *sidecar_path)",
        "{",
        "    std::call_once(voxels_once, [dll_path, sidecar_path] {",
        "        if (dll_path) {",
        "            voxels_path = dll_path;",
        "        } else {",
        "            // Playback loads exports directly; deployed wrappers receive the path through Init.",
        '            const char *home = std::getenv("HOME");',
        "            if (!home)",
        '                throw std::runtime_error("HOME is not set; call Init with the Voxels DLL path");',
        '            voxels_path = std::string(home) + "/Documents/Se2-Game2/VRage.Voxels.Native.dll";',
        "        }",
        "",
        "        if (!load_dll(&voxels_image, voxels_path.c_str(), sidecar_path))",
        '            throw std::runtime_error("Failed to load VRage.Voxels.Native.dll");',
    ]
    for name, _ in signatures:
        lines += [
            f'        p{name} = reinterpret_cast<{name}_t>(get_export("{name}"));',
            f"        if (!p{name})",
            f'            throw std::runtime_error("Missing Voxels export: {name}");',
        ]
    lines += ["    });", "}", "}", "", 'extern "C" {', "", "void Init(const char *dll_path, const char *sidecar_path)", "{", "    initialize(dll_path, sidecar_path);", "}", ""]

    for name, signature in signatures:
        ret = cpp_type(signature["ret"])
        names = parameter_names(signature)
        declarations = ", ".join(f"{cpp_type(param)} {param_name}"
                                 for param, param_name in zip(signature["params"], names)) or "void"
        arguments = [f"&{param_name}" if param["kind"] == "struct" else param_name
                     for param, param_name in zip(signature["params"], names)]
        lines += [f"{ret} {name}({declarations})", "{", "    ensure_thread_info();"]
        if name == "RegisterAssertionCallback":
            lines += [
                f"    sysv_assertion_callback = {names[0]};",
                "    pRegisterAssertionCallback(reinterpret_cast<void *>(&assertion_bridge));",
            ]
        elif signature["ret"]["kind"] == "struct":
            lines += [
                f"    {ret} result;",
                f"    p{name}(&result{', ' if arguments else ''}{', '.join(arguments)});",
                "    return result;",
            ]
        else:
            call = f"p{name}({', '.join(arguments)})"
            lines.append(f"    {call};" if ret == "void" else f"    return {call};")
        lines += ["}", ""]
    lines += ["void UnregisterAssertionCallback(void)", "{", "}", "", "}", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    OUTPUT.write_text(emit(load_signatures()), encoding="utf-8")
