#!/usr/bin/env python3
"""Generate VRage.KytheraV2.Native forwarders from decompiled P/Invokes."""

import re
from pathlib import Path

from csharp_pinvoke import (
    CPP_TYPES,
    load_generator_declarations,
    normalize_type,
    parameter_names,
)

ROOT = Path(__file__).parent.parent
OUTPUT = ROOT / "src/KytheraV2.cpp"

PRIMITIVES = {
    "void": "void",
    "byte": "u1",
    "int": "i4",
    "uint": "u4",
    "ulong": "u8",
    "float": "r4",
    "double": "r8",
    "nint": "ptr",
    "IntPtr": "ptr",
}
# Takes the managed callback table; its function pointers need System V to
# Microsoft x64 bridges.
CREATE_CORE = "KytV2_CreateCore"


def lower_type(value, modifier=None):
    value = normalize_type(value)
    # Structs only cross by reference, so every array, ref, out and pointer
    # argument is a plain pointer on both sides.
    if modifier in {"ref", "out", "in"} or value.endswith("*") or value.endswith("[]"):
        return {"kind": "ptr"}
    if value in PRIMITIVES:
        return {"kind": PRIMITIVES[value]}
    raise SystemExit(f"unsupported Kythera C# ABI type: {value}")


def load_signatures(declarations):
    signatures = {}
    for declaration in declarations:
        signature = {
            "ret": lower_type(declaration["ret"]),
            "params": [
                dict(lower_type(param["type"], param["modifier"]), n=param["name"])
                for param in declaration["params"]
            ],
        }
        previous = signatures.setdefault(declaration["entry_point"], signature)
        if previous != signature:
            raise SystemExit(f"conflicting signature for {declaration['entry_point']}")
    for name in signatures:
        if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", name):
            raise SystemExit(f"unsupported export name: {name}")
    if signatures.get(CREATE_CORE) != {
        "ret": {"kind": "ptr"},
        "params": [{"kind": "ptr", "n": "callbacks"}],
    }:
        raise SystemExit(f"unexpected {CREATE_CORE} signature")
    return sorted(signatures.items())


def cpp_type(value):
    try:
        return CPP_TYPES[value["kind"]]
    except KeyError:
        raise SystemExit(f"unsupported ABI kind: {value['kind']}") from None


def emit(signatures):
    lines = [
        "// Generated by tools/generate_kythera_wrapper.py. Do not edit.",
        "#include <cstdint>",
        "#include <cstdlib>",
        "#include <mutex>",
        "#include <stdexcept>",
        "",
        '#include "dll_loader.h"',
        "",
        "namespace {",
        "// KytheraNative.BridgeCallbacks. The managed side sets only",
        "// RequestBackgroundWork; Kythera routes memory through its own hooks.",
        "struct BridgeCallbacks {",
        "    void *allocate;",
        "    void *deallocate;",
        "    void *reallocate;",
        "    void *allocate_and_clear;",
        "    void *request_background_work;",
        "};",
        "",
        "pe_image kythera_image;",
        "std::once_flag kythera_once;",
        "// The bridge may keep the table's address, so it outlives the call.",
        "BridgeCallbacks pe_callbacks;",
        "void (*sysv_request_background_work)();",
        "",
        "void WINAPI request_background_work_bridge()",
        "{",
        "    sysv_request_background_work();",
        "}",
        "",
        "// Every call, not once per thread: each wrapper library points GS at its",
        "// own TEB, so a Physics or Slug call on this thread leaves GS on theirs.",
        "void ensure_thread_info()",
        "{",
        "    if (!kythera_image.image)",
        '        throw std::runtime_error("KytheraV2 is not initialized; call Init first");',
        "    if (!setup_nt_threadinfo(nullptr))",
        "        std::abort();",
        "    pe_ensure_tls_for_loaded_images();",
        "}",
        "",
    ]

    for name, signature in signatures:
        params = ", ".join(cpp_type(param) for param in signature["params"]) or "void"
        lines.append(
            f"using {name}_t = {cpp_type(signature['ret'])}(WINAPI *)({params});"
        )
        lines.append(f"{name}_t p{name};")

    lines += [
        "",
        "void initialize(const char *dll_path, const char *sidecar_path)",
        "{",
        "    if (!dll_path)",
        '        throw std::invalid_argument("KytheraV2 Init requires a DLL path");',
        "    std::call_once(kythera_once, [dll_path, sidecar_path] {",
        "        // Also loads the Kythera_*.dll imports from the same directory.",
        "        if (!load_dll(&kythera_image, dll_path, sidecar_path))",
        '            throw std::runtime_error("Failed to load VRage.KytheraV2.Native.dll");',
    ]
    for name, _ in signatures:
        lines += [
            f'        p{name} = reinterpret_cast<{name}_t>(get_export("{name}"));',
            f"        if (!p{name})",
            f'            throw std::runtime_error("Missing KytheraV2 export: {name}");',
        ]
    lines += [
        "    });",
        "}",
        "}",
        "",
        'extern "C" {',
        "",
        "void Init(const char *dll_path, const char *sidecar_path)",
        "{",
        "    initialize(dll_path, sidecar_path);",
        "}",
        "",
    ]

    for name, signature in signatures:
        ret = cpp_type(signature["ret"])
        names = parameter_names(signature["params"])
        declarations = (
            ", ".join(
                f"{cpp_type(param)} {param_name}"
                for param, param_name in zip(signature["params"], names)
            )
            or "void"
        )
        lines += [f"{ret} {name}({declarations})", "{", "    ensure_thread_info();"]
        if name == CREATE_CORE:
            lines += [
                f"    auto *managed = static_cast<const BridgeCallbacks *>({names[0]});",
                "    if (managed->allocate || managed->deallocate || managed->reallocate ||",
                "        managed->allocate_and_clear)",
                '        throw std::runtime_error("KytheraV2 memory callbacks are not bridged");',
                "    pe_callbacks = {};",
                "    sysv_request_background_work =",
                "        reinterpret_cast<void (*)()>(managed->request_background_work);",
                "    if (sysv_request_background_work)",
                "        pe_callbacks.request_background_work =",
                "            reinterpret_cast<void *>(&request_background_work_bridge);",
                f"    return p{name}(&pe_callbacks);",
            ]
        else:
            call = f"p{name}({', '.join(names)})"
            lines.append(f"    {call};" if ret == "void" else f"    return {call};")
        lines += ["}", ""]
    lines += ["}", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    declarations = load_generator_declarations("VRage.AI", "VRage.KytheraV2.Native.dll")
    source = emit(load_signatures(declarations))
    OUTPUT.write_text(source, encoding="utf-8")
