#!/usr/bin/env python3
"""Generate VRage.Voxels.Native forwarders from decompiled P/Invokes."""

import re
from pathlib import Path

from csharp_pinvoke import CPP_TYPES, load_generator_declarations, normalize_type, parameter_names


ROOT = Path(__file__).parent.parent
OUTPUT = ROOT / "src/Voxels.cpp"

PRIMITIVES = {
    "void": "void", "bool": "bool4", "byte": "u1", "int": "i4",
    "float": "r4", "nint": "ptr", "IntPtr": "ptr", "nuint": "u8",
    "UIntPtr": "u8",
}
STRUCTS = {
    "Vector2": 8, "Vector3": 12, "Vector3I": 12,
    "AmbientOcclusionArgs": 28, "MapSet": 56, "DetailMapData": 56,
}
BYTE_ENUMS = {"VrSewOperation", "GeneratedVertexProtocol"}
LOCAL_EXPORTS = {"UnregisterAssertionCallback"}


def lower_type(value, modifier=None):
    value = normalize_type(value)
    if modifier in {"ref", "out", "in"} or value.endswith("*"):
        return {"kind": "ptr"}
    if value in PRIMITIVES:
        return {"kind": PRIMITIVES[value]}
    if any(value == name or value.endswith(f".{name}") for name in BYTE_ENUMS):
        return {"kind": "u1"}
    for name, size in STRUCTS.items():
        if value == name or value.endswith(f".{name}"):
            return {"kind": "struct", "type": name, "size": size}
    raise SystemExit(f"unsupported Voxels C# ABI type: {value}")


def load_signatures(declarations):
    signatures = {}
    for declaration in declarations:
        signature = {
            "ret": lower_type(declaration["ret"]),
            "params": [dict(lower_type(param["type"], param["modifier"]), n=param["name"])
                       for param in declaration["params"]],
        }
        previous = signatures.setdefault(declaration["entry_point"], signature)
        if previous != signature:
            raise SystemExit(f"conflicting signature for {declaration['entry_point']}")
    for name in signatures:
        if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", name):
            raise SystemExit(f"unsupported export name: {name}")
    return sorted(signatures.items())


def cpp_type(value):
    if value["kind"] == "struct":
        type_name = value.get("type", "").rsplit(".", 1)[-1]
        expected_size = STRUCTS.get(type_name)
        if expected_size != value.get("size"):
            raise SystemExit(f"unsupported struct ABI: {value}")
        return type_name
    try:
        return CPP_TYPES[value["kind"]]
    except KeyError:
        raise SystemExit(f"unsupported ABI kind: {value['kind']}") from None


def emit(signatures):
    lines = [
        "// Generated by tools/generate_voxels_wrapper.py. Do not edit.",
        "#include <cstdint>",
        "#include <cstdlib>",
        "#include <cstring>",
        "#include <mutex>",
        "#include <stdexcept>",
        "",
        '#include "dll_loader.h"',
        "",
        "struct Vector2 { float x, y; };",
        "struct Vector3 { float x, y, z; };",
        "struct Vector3I { int32_t x, y, z; };",
        "",
        "struct AmbientOcclusionArgs {",
        "    float values[7];",
        "};",
        "struct alignas(8) MapSet { uint8_t values[56]; };",
        "struct alignas(8) DetailMapData { uint8_t values[56]; };",
        "",
        "static_assert(sizeof(Vector2) == 8);",
        "static_assert(sizeof(Vector3) == 12);",
        "static_assert(sizeof(Vector3I) == 12);",
        "static_assert(sizeof(AmbientOcclusionArgs) == 28);",
        "static_assert(sizeof(MapSet) == 56);",
        "static_assert(sizeof(DetailMapData) == 56);",
        "",
        "namespace {",
        "pe_image voxels_image;",
        "std::once_flag voxels_once;",
        "thread_local bool voxels_thread_ready;",
        "void *sysv_assertion_callback;",
        "",
        "void WINAPI assertion_bridge(const char *message)",
        "{",
        "    if (sysv_assertion_callback)",
        "        reinterpret_cast<void (*)(const char *)>(sysv_assertion_callback)(message);",
        "}",
        "",
        "template<typename T>",
        "uint64_t aggregate_bits(const T &value)",
        "{",
        "    static_assert(sizeof(T) <= sizeof(uint64_t));",
        "    uint64_t result = 0;",
        "    std::memcpy(&result, &value, sizeof(value));",
        "    return result;",
        "}",
        "",
        "void initialize(const char *dll_path, const char *sidecar_path);",
        "",
        "void ensure_thread_info()",
        "{",
        "    if (!voxels_image.image)",
        '        throw std::runtime_error("Voxels is not initialized; call Init first");',
        "    if (voxels_thread_ready)",
        "        return;",
        "    if (!setup_nt_threadinfo(nullptr))",
        "        std::abort();",
        "    pe_ensure_tls_for_loaded_images();",
        "    voxels_thread_ready = true;",
        "}",
        "",
    ]

    for name, signature in signatures:
        if name in LOCAL_EXPORTS:
            continue
        ret = signature["ret"]
        pe_ret = "void" if ret["kind"] == "struct" else cpp_type(ret)
        params = []
        if ret["kind"] == "struct":
            params.append(f"{cpp_type(ret)} *")
        params.extend((f"{cpp_type(param)} *" if param["size"] > 8 else f"uint{param['size'] * 8}_t")
                      if param["kind"] == "struct" else cpp_type(param)
                      for param in signature["params"])
        lines.append(f"using {name}_t = {pe_ret}(WINAPI *)({', '.join(params) or 'void'});")
        lines.append(f"{name}_t p{name};")

    lines += [
        "",
        "void initialize(const char *dll_path, const char *sidecar_path)",
        "{",
        "    if (!dll_path)",
        '        throw std::invalid_argument("Voxels Init requires a DLL path");',
        "    std::call_once(voxels_once, [dll_path, sidecar_path] {",
        "        if (!load_dll(&voxels_image, dll_path, sidecar_path))",
        '            throw std::runtime_error("Failed to load VRage.Voxels.Native.dll");',
    ]
    for name, _ in signatures:
        if name in LOCAL_EXPORTS:
            continue
        lines += [
            f'        p{name} = reinterpret_cast<{name}_t>(get_export("{name}"));',
            f"        if (!p{name})",
            f'            throw std::runtime_error("Missing Voxels export: {name}");',
        ]
    lines += ["    });", "}", "}", "", 'extern "C" {', "", "void Init(const char *dll_path, const char *sidecar_path)", "{", "    initialize(dll_path, sidecar_path);", "}", ""]

    for name, signature in signatures:
        ret = cpp_type(signature["ret"])
        names = parameter_names(signature["params"])
        declarations = ", ".join(f"{cpp_type(param)} {param_name}"
                                  for param, param_name in zip(signature["params"], names)) or "void"
        if name in LOCAL_EXPORTS:
            lines += [f"{ret} {name}({declarations})", "{", "    sysv_assertion_callback = nullptr;", "}", ""]
            continue
        arguments = [(f"&{param_name}_pe" if param["size"] > 8 else f"aggregate_bits({param_name})")
                     if param["kind"] == "struct" else param_name
                      for param, param_name in zip(signature["params"], names)]
        lines += [f"{ret} {name}({declarations})", "{", "    ensure_thread_info();"]
        for param, param_name in zip(signature["params"], names):
            if param["kind"] == "struct" and param["size"] > 8:
                lines.append(f"    alignas(16) {cpp_type(param)} {param_name}_pe = {param_name};")
        if name == "RegisterAssertionCallback":
            lines += [
                f"    sysv_assertion_callback = {names[0]};",
                "    pRegisterAssertionCallback(reinterpret_cast<void *>(&assertion_bridge));",
            ]
        elif signature["ret"]["kind"] == "struct":
            lines += [
                f"    alignas(16) {ret} result;",
                f"    p{name}(&result{', ' if arguments else ''}{', '.join(arguments)});",
                "    return result;",
            ]
        else:
            call = f"p{name}({', '.join(arguments)})"
            lines.append(f"    {call};" if ret == "void" else f"    return {call};")
        lines += ["}", ""]
    lines += ["}", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    declarations = load_generator_declarations("VRage.Voxels", "VRage.Voxels.Native.dll")
    source = emit(load_signatures(declarations))
    OUTPUT.write_text(source, encoding="utf-8")
