// Generated by tools/generate_kythera_wrapper.py. Do not edit.
#include <cstdint>
#include <cstdlib>
#include <mutex>
#include <stdexcept>

#include "dll_loader.h"

namespace {
// KytheraNative.BridgeCallbacks. The managed side sets only
// RequestBackgroundWork; Kythera routes memory through its own hooks.
struct BridgeCallbacks {
    void *allocate;
    void *deallocate;
    void *reallocate;
    void *allocate_and_clear;
    void *request_background_work;
};

pe_image kythera_image;
std::once_flag kythera_once;
// The bridge may keep the table's address, so it outlives the call.
BridgeCallbacks pe_callbacks;
void (*sysv_request_background_work)();

void WINAPI request_background_work_bridge()
{
    sysv_request_background_work();
}

// Every call, not once per thread: each wrapper library points GS at its
// own TEB, so a Physics or Slug call on this thread leaves GS on theirs.
void ensure_thread_info()
{
    if (!kythera_image.image)
        throw std::runtime_error("KytheraV2 is not initialized; call Init first");
    if (!setup_nt_threadinfo(nullptr))
        std::abort();
    pe_ensure_tls_for_loaded_images();
}

using KytV2_Agent_CancelNextLeg_t = void(WINAPI *)(uint32_t);
KytV2_Agent_CancelNextLeg_t pKytV2_Agent_CancelNextLeg;
using KytV2_Agent_GetPath_t = int32_t(WINAPI *)(uint32_t, void *, void *, void *);
KytV2_Agent_GetPath_t pKytV2_Agent_GetPath;
using KytV2_Agent_HasNextLeg_t = int32_t(WINAPI *)(uint32_t);
KytV2_Agent_HasNextLeg_t pKytV2_Agent_HasNextLeg;
using KytV2_Agent_QueueNextLeg_t = int32_t(WINAPI *)(uint32_t, void *, uint32_t, float, float, float, float, int32_t);
KytV2_Agent_QueueNextLeg_t pKytV2_Agent_QueueNextLeg;
using KytV2_Agent_RequestPath_t = int32_t(WINAPI *)(uint32_t, void *, uint32_t, float, float, float, float, float, float, float, int32_t, int32_t);
KytV2_Agent_RequestPath_t pKytV2_Agent_RequestPath;
using KytV2_Agent_SetArrivalDeceleration_t = void(WINAPI *)(uint32_t, int32_t);
KytV2_Agent_SetArrivalDeceleration_t pKytV2_Agent_SetArrivalDeceleration;
using KytV2_Agent_Stop_t = void(WINAPI *)(uint32_t);
KytV2_Agent_Stop_t pKytV2_Agent_Stop;
using KytV2_Agent_Tick_t = int32_t(WINAPI *)(uint32_t, float, float, float, float, void *);
KytV2_Agent_Tick_t pKytV2_Agent_Tick;
using KytV2_CanSurfacePathTo_t = int32_t(WINAPI *)(uint32_t, float, float, float, float, float, float);
KytV2_CanSurfacePathTo_t pKytV2_CanSurfacePathTo;
using KytV2_CreateAgent_t = uint32_t(WINAPI *)(float, float, float);
KytV2_CreateAgent_t pKytV2_CreateAgent;
using KytV2_CreateCore_t = void *(WINAPI *)(void *);
KytV2_CreateCore_t pKytV2_CreateCore;
using KytV2_CreateFlightAgent_t = uint32_t(WINAPI *)(float, float, float);
KytV2_CreateFlightAgent_t pKytV2_CreateFlightAgent;
using KytV2_CreateFlightNavMesh_t = uint32_t(WINAPI *)(double, int32_t, int32_t, int32_t);
KytV2_CreateFlightNavMesh_t pKytV2_CreateFlightNavMesh;
using KytV2_CreateFlightNavigation_t = void *(WINAPI *)(void);
KytV2_CreateFlightNavigation_t pKytV2_CreateFlightNavigation;
using KytV2_CreateGroundNavigation_t = void *(WINAPI *)(void);
KytV2_CreateGroundNavigation_t pKytV2_CreateGroundNavigation;
using KytV2_CreateNavMesh_t = uint32_t(WINAPI *)(void *, float, float, float, float, float, float, int32_t, int32_t, void *);
KytV2_CreateNavMesh_t pKytV2_CreateNavMesh;
using KytV2_CreatePhysicalWorldModel_t = void(WINAPI *)(void);
KytV2_CreatePhysicalWorldModel_t pKytV2_CreatePhysicalWorldModel;
using KytV2_CreateSurfaceAgent_t = uint32_t(WINAPI *)(float, float, float);
KytV2_CreateSurfaceAgent_t pKytV2_CreateSurfaceAgent;
using KytV2_CreateSurfaceNavMesh_t = uint32_t(WINAPI *)(float, float, float, int32_t, float, int32_t, float, int32_t);
KytV2_CreateSurfaceNavMesh_t pKytV2_CreateSurfaceNavMesh;
using KytV2_CreateSurfaceNavigation_t = void *(WINAPI *)(void);
KytV2_CreateSurfaceNavigation_t pKytV2_CreateSurfaceNavigation;
using KytV2_Destroy_t = void(WINAPI *)(void);
KytV2_Destroy_t pKytV2_Destroy;
using KytV2_DestroyAgent_t = void(WINAPI *)(uint32_t);
KytV2_DestroyAgent_t pKytV2_DestroyAgent;
using KytV2_DestroyCover_t = void(WINAPI *)(void);
KytV2_DestroyCover_t pKytV2_DestroyCover;
using KytV2_DestroyFlightAgent_t = void(WINAPI *)(uint32_t);
KytV2_DestroyFlightAgent_t pKytV2_DestroyFlightAgent;
using KytV2_DestroyFlightNavMesh_t = void(WINAPI *)(uint32_t);
KytV2_DestroyFlightNavMesh_t pKytV2_DestroyFlightNavMesh;
using KytV2_DestroyGroundNavigation_t = void(WINAPI *)(void);
KytV2_DestroyGroundNavigation_t pKytV2_DestroyGroundNavigation;
using KytV2_DestroyNavMesh_t = void(WINAPI *)(void *, uint32_t);
KytV2_DestroyNavMesh_t pKytV2_DestroyNavMesh;
using KytV2_DestroyPhysicalWorldModel_t = void(WINAPI *)(void);
KytV2_DestroyPhysicalWorldModel_t pKytV2_DestroyPhysicalWorldModel;
using KytV2_DestroySurfaceAgent_t = void(WINAPI *)(uint32_t);
KytV2_DestroySurfaceAgent_t pKytV2_DestroySurfaceAgent;
using KytV2_DestroySurfaceNavMesh_t = void(WINAPI *)(uint32_t);
KytV2_DestroySurfaceNavMesh_t pKytV2_DestroySurfaceNavMesh;
using KytV2_DestroySurfaceNavigation_t = void(WINAPI *)(void);
KytV2_DestroySurfaceNavigation_t pKytV2_DestroySurfaceNavigation;
using KytV2_DiagnoseCoverState_t = int32_t(WINAPI *)(uint32_t, float, float, float, float, void *, int32_t);
KytV2_DiagnoseCoverState_t pKytV2_DiagnoseCoverState;
using KytV2_DoBackgroundWork_t = int32_t(WINAPI *)(void *);
KytV2_DoBackgroundWork_t pKytV2_DoBackgroundWork;
using KytV2_DumpSurfaceTriangleComparison_t = void(WINAPI *)(uint32_t, void *, void *);
KytV2_DumpSurfaceTriangleComparison_t pKytV2_DumpSurfaceTriangleComparison;
using KytV2_FillNavMeshTriangles_t = int32_t(WINAPI *)(void *, uint32_t, void *, int32_t);
KytV2_FillNavMeshTriangles_t pKytV2_FillNavMeshTriangles;
using KytV2_FindAvoidanceVelocity_t = int32_t(WINAPI *)(void *, uint32_t, float, float, float, float, float, float, float, float, float, float, void *, int32_t, float, float, float, void *, void *, void *);
KytV2_FindAvoidanceVelocity_t pKytV2_FindAvoidanceVelocity;
using KytV2_FindNearestPoint_t = int32_t(WINAPI *)(void *, uint32_t, float, float, float, float, void *, void *, void *);
KytV2_FindNearestPoint_t pKytV2_FindNearestPoint;
using KytV2_FindPath_t = int32_t(WINAPI *)(void *, uint32_t, float, float, float, float, float, float, float, int32_t, void *, void *, int32_t);
KytV2_FindPath_t pKytV2_FindPath;
using KytV2_FindSurfacePath_t = int32_t(WINAPI *)(uint32_t, float, float, float, float, float, float, void *, void *);
KytV2_FindSurfacePath_t pKytV2_FindSurfacePath;
using KytV2_FlightAgent_GetPath_t = int32_t(WINAPI *)(uint32_t, void *, void *, void *);
KytV2_FlightAgent_GetPath_t pKytV2_FlightAgent_GetPath;
using KytV2_FlightAgent_RequestPath_t = int32_t(WINAPI *)(uint32_t, uint32_t, float, float, float, float, float, float, int32_t);
KytV2_FlightAgent_RequestPath_t pKytV2_FlightAgent_RequestPath;
using KytV2_FlightAgent_Stop_t = void(WINAPI *)(uint32_t);
KytV2_FlightAgent_Stop_t pKytV2_FlightAgent_Stop;
using KytV2_FlightAgent_Tick_t = int32_t(WINAPI *)(uint32_t, float, float, float, float, void *);
KytV2_FlightAgent_Tick_t pKytV2_FlightAgent_Tick;
using KytV2_FlightGetGenerationPercentage_t = float(WINAPI *)(uint32_t);
KytV2_FlightGetGenerationPercentage_t pKytV2_FlightGetGenerationPercentage;
using KytV2_FlightHasChangesPending_t = int32_t(WINAPI *)(uint32_t);
KytV2_FlightHasChangesPending_t pKytV2_FlightHasChangesPending;
using KytV2_FlightIsGenerating_t = int32_t(WINAPI *)(uint32_t);
KytV2_FlightIsGenerating_t pKytV2_FlightIsGenerating;
using KytV2_FlightMarkDirty_t = void(WINAPI *)(uint32_t, float, float, float, float, float, float);
KytV2_FlightMarkDirty_t pKytV2_FlightMarkDirty;
using KytV2_FlightNavMesh_GetTrianglesAtomic_t = int32_t(WINAPI *)(uint32_t, int32_t, int32_t, void *);
KytV2_FlightNavMesh_GetTrianglesAtomic_t pKytV2_FlightNavMesh_GetTrianglesAtomic;
using KytV2_GetGenerationPercentage_t = float(WINAPI *)(void *, uint32_t);
KytV2_GetGenerationPercentage_t pKytV2_GetGenerationPercentage;
using KytV2_GetNavMeshTriangleCount_t = int32_t(WINAPI *)(void *, uint32_t);
KytV2_GetNavMeshTriangleCount_t pKytV2_GetNavMeshTriangleCount;
using KytV2_GetNavMeshTrianglesAtomic_t = int32_t(WINAPI *)(void *, uint32_t, void *);
KytV2_GetNavMeshTrianglesAtomic_t pKytV2_GetNavMeshTrianglesAtomic;
using KytV2_GetSurfaceNavMeshTrianglesAtomic_t = int32_t(WINAPI *)(uint32_t, void *);
KytV2_GetSurfaceNavMeshTrianglesAtomic_t pKytV2_GetSurfaceNavMeshTrianglesAtomic;
using KytV2_HasChangesPending_t = int32_t(WINAPI *)(void *, uint32_t);
KytV2_HasChangesPending_t pKytV2_HasChangesPending;
using KytV2_InitAvoidance_t = void(WINAPI *)(void);
KytV2_InitAvoidance_t pKytV2_InitAvoidance;
using KytV2_InitCover_t = void(WINAPI *)(void);
KytV2_InitCover_t pKytV2_InitCover;
using KytV2_InitPathPlanner_t = void(WINAPI *)(void);
KytV2_InitPathPlanner_t pKytV2_InitPathPlanner;
using KytV2_InitSurfacePathPlanner_t = void(WINAPI *)(void);
KytV2_InitSurfacePathPlanner_t pKytV2_InitSurfacePathPlanner;
using KytV2_IsGenerating_t = int32_t(WINAPI *)(void *, uint32_t);
KytV2_IsGenerating_t pKytV2_IsGenerating;
using KytV2_MarkDirty_t = void(WINAPI *)(void *, uint32_t, float, float, float, float, float, float);
KytV2_MarkDirty_t pKytV2_MarkDirty;
using KytV2_Octree_Create_t = void(WINAPI *)(int32_t, int32_t, double);
KytV2_Octree_Create_t pKytV2_Octree_Create;
using KytV2_Octree_Destroy_t = void(WINAPI *)(void);
KytV2_Octree_Destroy_t pKytV2_Octree_Destroy;
using KytV2_Octree_GenerateFromGeometry_t = int32_t(WINAPI *)(void *, int32_t, void *, int32_t, double, double, double, double, double, double);
KytV2_Octree_GenerateFromGeometry_t pKytV2_Octree_GenerateFromGeometry;
using KytV2_Octree_GetStats_t = void(WINAPI *)(void *, void *, void *);
KytV2_Octree_GetStats_t pKytV2_Octree_GetStats;
using KytV2_Octree_GetTriangleCount_t = int32_t(WINAPI *)(int32_t);
KytV2_Octree_GetTriangleCount_t pKytV2_Octree_GetTriangleCount;
using KytV2_Octree_GetTrianglesAtomic_t = int32_t(WINAPI *)(void *, int32_t, int32_t);
KytV2_Octree_GetTrianglesAtomic_t pKytV2_Octree_GetTrianglesAtomic;
using KytV2_QueryCoverPoints_t = int32_t(WINAPI *)(uint32_t, float, float, float, float, uint32_t, void *, void *);
KytV2_QueryCoverPoints_t pKytV2_QueryCoverPoints;
using KytV2_Raycast_t = int32_t(WINAPI *)(void *, uint32_t, float, float, float, float, float, float, void *, void *, void *);
KytV2_Raycast_t pKytV2_Raycast;
using KytV2_RemoveTiles_t = int32_t(WINAPI *)(void *, uint32_t, float, float, float, float, float, float);
KytV2_RemoveTiles_t pKytV2_RemoveTiles;
using KytV2_SetGeometry_t = void(WINAPI *)(void *, int32_t, void *, int32_t, float, float, float, float, float, float);
KytV2_SetGeometry_t pKytV2_SetGeometry;
using KytV2_SetMaxJobThreads_t = void(WINAPI *)(uint32_t);
KytV2_SetMaxJobThreads_t pKytV2_SetMaxJobThreads;
using KytV2_SetTestQuad_t = void(WINAPI *)(float, float, float, float);
KytV2_SetTestQuad_t pKytV2_SetTestQuad;
using KytV2_SetUpdateThread_t = void(WINAPI *)(void *);
KytV2_SetUpdateThread_t pKytV2_SetUpdateThread;
using KytV2_StartUpdate_t = void(WINAPI *)(void *, double);
KytV2_StartUpdate_t pKytV2_StartUpdate;
using KytV2_SurfaceAgent_RequestPath_t = int32_t(WINAPI *)(uint32_t, uint32_t, float, float, float, float, float, float);
KytV2_SurfaceAgent_RequestPath_t pKytV2_SurfaceAgent_RequestPath;
using KytV2_SurfaceAgent_Stop_t = void(WINAPI *)(uint32_t);
KytV2_SurfaceAgent_Stop_t pKytV2_SurfaceAgent_Stop;
using KytV2_SurfaceAgent_Tick_t = int32_t(WINAPI *)(uint32_t, float, float, float, float, float, float, float, float, float, float, void *);
KytV2_SurfaceAgent_Tick_t pKytV2_SurfaceAgent_Tick;
using KytV2_SurfaceGetGenerationPercentage_t = float(WINAPI *)(uint32_t);
KytV2_SurfaceGetGenerationPercentage_t pKytV2_SurfaceGetGenerationPercentage;
using KytV2_SurfaceHasChangesPending_t = int32_t(WINAPI *)(uint32_t);
KytV2_SurfaceHasChangesPending_t pKytV2_SurfaceHasChangesPending;
using KytV2_SurfaceIsGenerating_t = int32_t(WINAPI *)(uint32_t);
KytV2_SurfaceIsGenerating_t pKytV2_SurfaceIsGenerating;
using KytV2_SurfaceMarkDirty_t = void(WINAPI *)(uint32_t, float, float, float, float, float, float);
KytV2_SurfaceMarkDirty_t pKytV2_SurfaceMarkDirty;
using KytV2_TerminateJobSystem_t = void(WINAPI *)(void);
KytV2_TerminateJobSystem_t pKytV2_TerminateJobSystem;

void initialize(const char *dll_path, const char *sidecar_path)
{
    if (!dll_path)
        throw std::invalid_argument("KytheraV2 Init requires a DLL path");
    std::call_once(kythera_once, [dll_path, sidecar_path] {
        // Also loads the Kythera_*.dll imports from the same directory.
        if (!load_dll(&kythera_image, dll_path, sidecar_path))
            throw std::runtime_error("Failed to load VRage.KytheraV2.Native.dll");
        pKytV2_Agent_CancelNextLeg = reinterpret_cast<KytV2_Agent_CancelNextLeg_t>(get_export("KytV2_Agent_CancelNextLeg"));
        if (!pKytV2_Agent_CancelNextLeg)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_Agent_CancelNextLeg");
        pKytV2_Agent_GetPath = reinterpret_cast<KytV2_Agent_GetPath_t>(get_export("KytV2_Agent_GetPath"));
        if (!pKytV2_Agent_GetPath)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_Agent_GetPath");
        pKytV2_Agent_HasNextLeg = reinterpret_cast<KytV2_Agent_HasNextLeg_t>(get_export("KytV2_Agent_HasNextLeg"));
        if (!pKytV2_Agent_HasNextLeg)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_Agent_HasNextLeg");
        pKytV2_Agent_QueueNextLeg = reinterpret_cast<KytV2_Agent_QueueNextLeg_t>(get_export("KytV2_Agent_QueueNextLeg"));
        if (!pKytV2_Agent_QueueNextLeg)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_Agent_QueueNextLeg");
        pKytV2_Agent_RequestPath = reinterpret_cast<KytV2_Agent_RequestPath_t>(get_export("KytV2_Agent_RequestPath"));
        if (!pKytV2_Agent_RequestPath)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_Agent_RequestPath");
        pKytV2_Agent_SetArrivalDeceleration = reinterpret_cast<KytV2_Agent_SetArrivalDeceleration_t>(get_export("KytV2_Agent_SetArrivalDeceleration"));
        if (!pKytV2_Agent_SetArrivalDeceleration)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_Agent_SetArrivalDeceleration");
        pKytV2_Agent_Stop = reinterpret_cast<KytV2_Agent_Stop_t>(get_export("KytV2_Agent_Stop"));
        if (!pKytV2_Agent_Stop)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_Agent_Stop");
        pKytV2_Agent_Tick = reinterpret_cast<KytV2_Agent_Tick_t>(get_export("KytV2_Agent_Tick"));
        if (!pKytV2_Agent_Tick)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_Agent_Tick");
        pKytV2_CanSurfacePathTo = reinterpret_cast<KytV2_CanSurfacePathTo_t>(get_export("KytV2_CanSurfacePathTo"));
        if (!pKytV2_CanSurfacePathTo)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_CanSurfacePathTo");
        pKytV2_CreateAgent = reinterpret_cast<KytV2_CreateAgent_t>(get_export("KytV2_CreateAgent"));
        if (!pKytV2_CreateAgent)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_CreateAgent");
        pKytV2_CreateCore = reinterpret_cast<KytV2_CreateCore_t>(get_export("KytV2_CreateCore"));
        if (!pKytV2_CreateCore)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_CreateCore");
        pKytV2_CreateFlightAgent = reinterpret_cast<KytV2_CreateFlightAgent_t>(get_export("KytV2_CreateFlightAgent"));
        if (!pKytV2_CreateFlightAgent)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_CreateFlightAgent");
        pKytV2_CreateFlightNavMesh = reinterpret_cast<KytV2_CreateFlightNavMesh_t>(get_export("KytV2_CreateFlightNavMesh"));
        if (!pKytV2_CreateFlightNavMesh)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_CreateFlightNavMesh");
        pKytV2_CreateFlightNavigation = reinterpret_cast<KytV2_CreateFlightNavigation_t>(get_export("KytV2_CreateFlightNavigation"));
        if (!pKytV2_CreateFlightNavigation)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_CreateFlightNavigation");
        pKytV2_CreateGroundNavigation = reinterpret_cast<KytV2_CreateGroundNavigation_t>(get_export("KytV2_CreateGroundNavigation"));
        if (!pKytV2_CreateGroundNavigation)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_CreateGroundNavigation");
        pKytV2_CreateNavMesh = reinterpret_cast<KytV2_CreateNavMesh_t>(get_export("KytV2_CreateNavMesh"));
        if (!pKytV2_CreateNavMesh)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_CreateNavMesh");
        pKytV2_CreatePhysicalWorldModel = reinterpret_cast<KytV2_CreatePhysicalWorldModel_t>(get_export("KytV2_CreatePhysicalWorldModel"));
        if (!pKytV2_CreatePhysicalWorldModel)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_CreatePhysicalWorldModel");
        pKytV2_CreateSurfaceAgent = reinterpret_cast<KytV2_CreateSurfaceAgent_t>(get_export("KytV2_CreateSurfaceAgent"));
        if (!pKytV2_CreateSurfaceAgent)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_CreateSurfaceAgent");
        pKytV2_CreateSurfaceNavMesh = reinterpret_cast<KytV2_CreateSurfaceNavMesh_t>(get_export("KytV2_CreateSurfaceNavMesh"));
        if (!pKytV2_CreateSurfaceNavMesh)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_CreateSurfaceNavMesh");
        pKytV2_CreateSurfaceNavigation = reinterpret_cast<KytV2_CreateSurfaceNavigation_t>(get_export("KytV2_CreateSurfaceNavigation"));
        if (!pKytV2_CreateSurfaceNavigation)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_CreateSurfaceNavigation");
        pKytV2_Destroy = reinterpret_cast<KytV2_Destroy_t>(get_export("KytV2_Destroy"));
        if (!pKytV2_Destroy)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_Destroy");
        pKytV2_DestroyAgent = reinterpret_cast<KytV2_DestroyAgent_t>(get_export("KytV2_DestroyAgent"));
        if (!pKytV2_DestroyAgent)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_DestroyAgent");
        pKytV2_DestroyCover = reinterpret_cast<KytV2_DestroyCover_t>(get_export("KytV2_DestroyCover"));
        if (!pKytV2_DestroyCover)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_DestroyCover");
        pKytV2_DestroyFlightAgent = reinterpret_cast<KytV2_DestroyFlightAgent_t>(get_export("KytV2_DestroyFlightAgent"));
        if (!pKytV2_DestroyFlightAgent)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_DestroyFlightAgent");
        pKytV2_DestroyFlightNavMesh = reinterpret_cast<KytV2_DestroyFlightNavMesh_t>(get_export("KytV2_DestroyFlightNavMesh"));
        if (!pKytV2_DestroyFlightNavMesh)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_DestroyFlightNavMesh");
        pKytV2_DestroyGroundNavigation = reinterpret_cast<KytV2_DestroyGroundNavigation_t>(get_export("KytV2_DestroyGroundNavigation"));
        if (!pKytV2_DestroyGroundNavigation)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_DestroyGroundNavigation");
        pKytV2_DestroyNavMesh = reinterpret_cast<KytV2_DestroyNavMesh_t>(get_export("KytV2_DestroyNavMesh"));
        if (!pKytV2_DestroyNavMesh)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_DestroyNavMesh");
        pKytV2_DestroyPhysicalWorldModel = reinterpret_cast<KytV2_DestroyPhysicalWorldModel_t>(get_export("KytV2_DestroyPhysicalWorldModel"));
        if (!pKytV2_DestroyPhysicalWorldModel)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_DestroyPhysicalWorldModel");
        pKytV2_DestroySurfaceAgent = reinterpret_cast<KytV2_DestroySurfaceAgent_t>(get_export("KytV2_DestroySurfaceAgent"));
        if (!pKytV2_DestroySurfaceAgent)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_DestroySurfaceAgent");
        pKytV2_DestroySurfaceNavMesh = reinterpret_cast<KytV2_DestroySurfaceNavMesh_t>(get_export("KytV2_DestroySurfaceNavMesh"));
        if (!pKytV2_DestroySurfaceNavMesh)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_DestroySurfaceNavMesh");
        pKytV2_DestroySurfaceNavigation = reinterpret_cast<KytV2_DestroySurfaceNavigation_t>(get_export("KytV2_DestroySurfaceNavigation"));
        if (!pKytV2_DestroySurfaceNavigation)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_DestroySurfaceNavigation");
        pKytV2_DiagnoseCoverState = reinterpret_cast<KytV2_DiagnoseCoverState_t>(get_export("KytV2_DiagnoseCoverState"));
        if (!pKytV2_DiagnoseCoverState)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_DiagnoseCoverState");
        pKytV2_DoBackgroundWork = reinterpret_cast<KytV2_DoBackgroundWork_t>(get_export("KytV2_DoBackgroundWork"));
        if (!pKytV2_DoBackgroundWork)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_DoBackgroundWork");
        pKytV2_DumpSurfaceTriangleComparison = reinterpret_cast<KytV2_DumpSurfaceTriangleComparison_t>(get_export("KytV2_DumpSurfaceTriangleComparison"));
        if (!pKytV2_DumpSurfaceTriangleComparison)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_DumpSurfaceTriangleComparison");
        pKytV2_FillNavMeshTriangles = reinterpret_cast<KytV2_FillNavMeshTriangles_t>(get_export("KytV2_FillNavMeshTriangles"));
        if (!pKytV2_FillNavMeshTriangles)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_FillNavMeshTriangles");
        pKytV2_FindAvoidanceVelocity = reinterpret_cast<KytV2_FindAvoidanceVelocity_t>(get_export("KytV2_FindAvoidanceVelocity"));
        if (!pKytV2_FindAvoidanceVelocity)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_FindAvoidanceVelocity");
        pKytV2_FindNearestPoint = reinterpret_cast<KytV2_FindNearestPoint_t>(get_export("KytV2_FindNearestPoint"));
        if (!pKytV2_FindNearestPoint)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_FindNearestPoint");
        pKytV2_FindPath = reinterpret_cast<KytV2_FindPath_t>(get_export("KytV2_FindPath"));
        if (!pKytV2_FindPath)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_FindPath");
        pKytV2_FindSurfacePath = reinterpret_cast<KytV2_FindSurfacePath_t>(get_export("KytV2_FindSurfacePath"));
        if (!pKytV2_FindSurfacePath)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_FindSurfacePath");
        pKytV2_FlightAgent_GetPath = reinterpret_cast<KytV2_FlightAgent_GetPath_t>(get_export("KytV2_FlightAgent_GetPath"));
        if (!pKytV2_FlightAgent_GetPath)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_FlightAgent_GetPath");
        pKytV2_FlightAgent_RequestPath = reinterpret_cast<KytV2_FlightAgent_RequestPath_t>(get_export("KytV2_FlightAgent_RequestPath"));
        if (!pKytV2_FlightAgent_RequestPath)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_FlightAgent_RequestPath");
        pKytV2_FlightAgent_Stop = reinterpret_cast<KytV2_FlightAgent_Stop_t>(get_export("KytV2_FlightAgent_Stop"));
        if (!pKytV2_FlightAgent_Stop)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_FlightAgent_Stop");
        pKytV2_FlightAgent_Tick = reinterpret_cast<KytV2_FlightAgent_Tick_t>(get_export("KytV2_FlightAgent_Tick"));
        if (!pKytV2_FlightAgent_Tick)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_FlightAgent_Tick");
        pKytV2_FlightGetGenerationPercentage = reinterpret_cast<KytV2_FlightGetGenerationPercentage_t>(get_export("KytV2_FlightGetGenerationPercentage"));
        if (!pKytV2_FlightGetGenerationPercentage)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_FlightGetGenerationPercentage");
        pKytV2_FlightHasChangesPending = reinterpret_cast<KytV2_FlightHasChangesPending_t>(get_export("KytV2_FlightHasChangesPending"));
        if (!pKytV2_FlightHasChangesPending)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_FlightHasChangesPending");
        pKytV2_FlightIsGenerating = reinterpret_cast<KytV2_FlightIsGenerating_t>(get_export("KytV2_FlightIsGenerating"));
        if (!pKytV2_FlightIsGenerating)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_FlightIsGenerating");
        pKytV2_FlightMarkDirty = reinterpret_cast<KytV2_FlightMarkDirty_t>(get_export("KytV2_FlightMarkDirty"));
        if (!pKytV2_FlightMarkDirty)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_FlightMarkDirty");
        pKytV2_FlightNavMesh_GetTrianglesAtomic = reinterpret_cast<KytV2_FlightNavMesh_GetTrianglesAtomic_t>(get_export("KytV2_FlightNavMesh_GetTrianglesAtomic"));
        if (!pKytV2_FlightNavMesh_GetTrianglesAtomic)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_FlightNavMesh_GetTrianglesAtomic");
        pKytV2_GetGenerationPercentage = reinterpret_cast<KytV2_GetGenerationPercentage_t>(get_export("KytV2_GetGenerationPercentage"));
        if (!pKytV2_GetGenerationPercentage)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_GetGenerationPercentage");
        pKytV2_GetNavMeshTriangleCount = reinterpret_cast<KytV2_GetNavMeshTriangleCount_t>(get_export("KytV2_GetNavMeshTriangleCount"));
        if (!pKytV2_GetNavMeshTriangleCount)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_GetNavMeshTriangleCount");
        pKytV2_GetNavMeshTrianglesAtomic = reinterpret_cast<KytV2_GetNavMeshTrianglesAtomic_t>(get_export("KytV2_GetNavMeshTrianglesAtomic"));
        if (!pKytV2_GetNavMeshTrianglesAtomic)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_GetNavMeshTrianglesAtomic");
        pKytV2_GetSurfaceNavMeshTrianglesAtomic = reinterpret_cast<KytV2_GetSurfaceNavMeshTrianglesAtomic_t>(get_export("KytV2_GetSurfaceNavMeshTrianglesAtomic"));
        if (!pKytV2_GetSurfaceNavMeshTrianglesAtomic)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_GetSurfaceNavMeshTrianglesAtomic");
        pKytV2_HasChangesPending = reinterpret_cast<KytV2_HasChangesPending_t>(get_export("KytV2_HasChangesPending"));
        if (!pKytV2_HasChangesPending)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_HasChangesPending");
        pKytV2_InitAvoidance = reinterpret_cast<KytV2_InitAvoidance_t>(get_export("KytV2_InitAvoidance"));
        if (!pKytV2_InitAvoidance)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_InitAvoidance");
        pKytV2_InitCover = reinterpret_cast<KytV2_InitCover_t>(get_export("KytV2_InitCover"));
        if (!pKytV2_InitCover)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_InitCover");
        pKytV2_InitPathPlanner = reinterpret_cast<KytV2_InitPathPlanner_t>(get_export("KytV2_InitPathPlanner"));
        if (!pKytV2_InitPathPlanner)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_InitPathPlanner");
        pKytV2_InitSurfacePathPlanner = reinterpret_cast<KytV2_InitSurfacePathPlanner_t>(get_export("KytV2_InitSurfacePathPlanner"));
        if (!pKytV2_InitSurfacePathPlanner)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_InitSurfacePathPlanner");
        pKytV2_IsGenerating = reinterpret_cast<KytV2_IsGenerating_t>(get_export("KytV2_IsGenerating"));
        if (!pKytV2_IsGenerating)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_IsGenerating");
        pKytV2_MarkDirty = reinterpret_cast<KytV2_MarkDirty_t>(get_export("KytV2_MarkDirty"));
        if (!pKytV2_MarkDirty)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_MarkDirty");
        pKytV2_Octree_Create = reinterpret_cast<KytV2_Octree_Create_t>(get_export("KytV2_Octree_Create"));
        if (!pKytV2_Octree_Create)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_Octree_Create");
        pKytV2_Octree_Destroy = reinterpret_cast<KytV2_Octree_Destroy_t>(get_export("KytV2_Octree_Destroy"));
        if (!pKytV2_Octree_Destroy)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_Octree_Destroy");
        pKytV2_Octree_GenerateFromGeometry = reinterpret_cast<KytV2_Octree_GenerateFromGeometry_t>(get_export("KytV2_Octree_GenerateFromGeometry"));
        if (!pKytV2_Octree_GenerateFromGeometry)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_Octree_GenerateFromGeometry");
        pKytV2_Octree_GetStats = reinterpret_cast<KytV2_Octree_GetStats_t>(get_export("KytV2_Octree_GetStats"));
        if (!pKytV2_Octree_GetStats)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_Octree_GetStats");
        pKytV2_Octree_GetTriangleCount = reinterpret_cast<KytV2_Octree_GetTriangleCount_t>(get_export("KytV2_Octree_GetTriangleCount"));
        if (!pKytV2_Octree_GetTriangleCount)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_Octree_GetTriangleCount");
        pKytV2_Octree_GetTrianglesAtomic = reinterpret_cast<KytV2_Octree_GetTrianglesAtomic_t>(get_export("KytV2_Octree_GetTrianglesAtomic"));
        if (!pKytV2_Octree_GetTrianglesAtomic)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_Octree_GetTrianglesAtomic");
        pKytV2_QueryCoverPoints = reinterpret_cast<KytV2_QueryCoverPoints_t>(get_export("KytV2_QueryCoverPoints"));
        if (!pKytV2_QueryCoverPoints)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_QueryCoverPoints");
        pKytV2_Raycast = reinterpret_cast<KytV2_Raycast_t>(get_export("KytV2_Raycast"));
        if (!pKytV2_Raycast)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_Raycast");
        pKytV2_RemoveTiles = reinterpret_cast<KytV2_RemoveTiles_t>(get_export("KytV2_RemoveTiles"));
        if (!pKytV2_RemoveTiles)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_RemoveTiles");
        pKytV2_SetGeometry = reinterpret_cast<KytV2_SetGeometry_t>(get_export("KytV2_SetGeometry"));
        if (!pKytV2_SetGeometry)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_SetGeometry");
        pKytV2_SetMaxJobThreads = reinterpret_cast<KytV2_SetMaxJobThreads_t>(get_export("KytV2_SetMaxJobThreads"));
        if (!pKytV2_SetMaxJobThreads)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_SetMaxJobThreads");
        pKytV2_SetTestQuad = reinterpret_cast<KytV2_SetTestQuad_t>(get_export("KytV2_SetTestQuad"));
        if (!pKytV2_SetTestQuad)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_SetTestQuad");
        pKytV2_SetUpdateThread = reinterpret_cast<KytV2_SetUpdateThread_t>(get_export("KytV2_SetUpdateThread"));
        if (!pKytV2_SetUpdateThread)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_SetUpdateThread");
        pKytV2_StartUpdate = reinterpret_cast<KytV2_StartUpdate_t>(get_export("KytV2_StartUpdate"));
        if (!pKytV2_StartUpdate)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_StartUpdate");
        pKytV2_SurfaceAgent_RequestPath = reinterpret_cast<KytV2_SurfaceAgent_RequestPath_t>(get_export("KytV2_SurfaceAgent_RequestPath"));
        if (!pKytV2_SurfaceAgent_RequestPath)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_SurfaceAgent_RequestPath");
        pKytV2_SurfaceAgent_Stop = reinterpret_cast<KytV2_SurfaceAgent_Stop_t>(get_export("KytV2_SurfaceAgent_Stop"));
        if (!pKytV2_SurfaceAgent_Stop)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_SurfaceAgent_Stop");
        pKytV2_SurfaceAgent_Tick = reinterpret_cast<KytV2_SurfaceAgent_Tick_t>(get_export("KytV2_SurfaceAgent_Tick"));
        if (!pKytV2_SurfaceAgent_Tick)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_SurfaceAgent_Tick");
        pKytV2_SurfaceGetGenerationPercentage = reinterpret_cast<KytV2_SurfaceGetGenerationPercentage_t>(get_export("KytV2_SurfaceGetGenerationPercentage"));
        if (!pKytV2_SurfaceGetGenerationPercentage)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_SurfaceGetGenerationPercentage");
        pKytV2_SurfaceHasChangesPending = reinterpret_cast<KytV2_SurfaceHasChangesPending_t>(get_export("KytV2_SurfaceHasChangesPending"));
        if (!pKytV2_SurfaceHasChangesPending)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_SurfaceHasChangesPending");
        pKytV2_SurfaceIsGenerating = reinterpret_cast<KytV2_SurfaceIsGenerating_t>(get_export("KytV2_SurfaceIsGenerating"));
        if (!pKytV2_SurfaceIsGenerating)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_SurfaceIsGenerating");
        pKytV2_SurfaceMarkDirty = reinterpret_cast<KytV2_SurfaceMarkDirty_t>(get_export("KytV2_SurfaceMarkDirty"));
        if (!pKytV2_SurfaceMarkDirty)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_SurfaceMarkDirty");
        pKytV2_TerminateJobSystem = reinterpret_cast<KytV2_TerminateJobSystem_t>(get_export("KytV2_TerminateJobSystem"));
        if (!pKytV2_TerminateJobSystem)
            throw std::runtime_error("Missing KytheraV2 export: KytV2_TerminateJobSystem");
    });
}
}

extern "C" {

void Init(const char *dll_path, const char *sidecar_path)
{
    initialize(dll_path, sidecar_path);
}

void KytV2_Agent_CancelNextLeg(uint32_t agentId)
{
    ensure_thread_info();
    pKytV2_Agent_CancelNextLeg(agentId);
}

int32_t KytV2_Agent_GetPath(uint32_t agentId, void * outWaypoints, void * outWaypointCount, void * outCurrentWaypointIndex)
{
    ensure_thread_info();
    return pKytV2_Agent_GetPath(agentId, outWaypoints, outWaypointCount, outCurrentWaypointIndex);
}

int32_t KytV2_Agent_HasNextLeg(uint32_t agentId)
{
    ensure_thread_info();
    return pKytV2_Agent_HasNextLeg(agentId);
}

int32_t KytV2_Agent_QueueNextLeg(uint32_t agentId, void * groundNav, uint32_t navMeshId, float endX, float endY, float endZ, float clampRadius, int32_t maxNodes)
{
    ensure_thread_info();
    return pKytV2_Agent_QueueNextLeg(agentId, groundNav, navMeshId, endX, endY, endZ, clampRadius, maxNodes);
}

int32_t KytV2_Agent_RequestPath(uint32_t agentId, void * groundNav, uint32_t navMeshId, float startX, float startY, float startZ, float endX, float endY, float endZ, float clampRadius, int32_t maxNodes, int32_t allowPartialResults)
{
    ensure_thread_info();
    return pKytV2_Agent_RequestPath(agentId, groundNav, navMeshId, startX, startY, startZ, endX, endY, endZ, clampRadius, maxNodes, allowPartialResults);
}

void KytV2_Agent_SetArrivalDeceleration(uint32_t agentId, int32_t enable)
{
    ensure_thread_info();
    pKytV2_Agent_SetArrivalDeceleration(agentId, enable);
}

void KytV2_Agent_Stop(uint32_t agentId)
{
    ensure_thread_info();
    pKytV2_Agent_Stop(agentId);
}

int32_t KytV2_Agent_Tick(uint32_t agentId, float agentPosX, float agentPosY, float agentPosZ, float deltaTime, void * outMoveData)
{
    ensure_thread_info();
    return pKytV2_Agent_Tick(agentId, agentPosX, agentPosY, agentPosZ, deltaTime, outMoveData);
}

int32_t KytV2_CanSurfacePathTo(uint32_t navMeshId, float startX, float startY, float startZ, float endX, float endY, float endZ)
{
    ensure_thread_info();
    return pKytV2_CanSurfacePathTo(navMeshId, startX, startY, startZ, endX, endY, endZ);
}

uint32_t KytV2_CreateAgent(float speed, float waypointTolerance, float lookAheadDistance)
{
    ensure_thread_info();
    return pKytV2_CreateAgent(speed, waypointTolerance, lookAheadDistance);
}

void * KytV2_CreateCore(void * callbacks)
{
    ensure_thread_info();
    auto *managed = static_cast<const BridgeCallbacks *>(callbacks);
    if (managed->allocate || managed->deallocate || managed->reallocate ||
        managed->allocate_and_clear)
        throw std::runtime_error("KytheraV2 memory callbacks are not bridged");
    pe_callbacks = {};
    sysv_request_background_work =
        reinterpret_cast<void (*)()>(managed->request_background_work);
    if (sysv_request_background_work)
        pe_callbacks.request_background_work =
            reinterpret_cast<void *>(&request_background_work_bridge);
    return pKytV2_CreateCore(&pe_callbacks);
}

uint32_t KytV2_CreateFlightAgent(float speed, float agentRadius, float lookAheadDistance)
{
    ensure_thread_info();
    return pKytV2_CreateFlightAgent(speed, agentRadius, lookAheadDistance);
}

uint32_t KytV2_CreateFlightNavMesh(double cellSize, int32_t treeDepth, int32_t minNavigableRadius, int32_t maxNavigableRadius)
{
    ensure_thread_info();
    return pKytV2_CreateFlightNavMesh(cellSize, treeDepth, minNavigableRadius, maxNavigableRadius);
}

void * KytV2_CreateFlightNavigation(void)
{
    ensure_thread_info();
    return pKytV2_CreateFlightNavigation();
}

void * KytV2_CreateGroundNavigation(void)
{
    ensure_thread_info();
    return pKytV2_CreateGroundNavigation();
}

uint32_t KytV2_CreateNavMesh(void * groundNav, float cellSize, float cellHeight, float agentHeight, float agentRadius, float agentMaxClimb, float agentMaxSlope, int32_t tileSize, int32_t borderSize, void * coverConfig)
{
    ensure_thread_info();
    return pKytV2_CreateNavMesh(groundNav, cellSize, cellHeight, agentHeight, agentRadius, agentMaxClimb, agentMaxSlope, tileSize, borderSize, coverConfig);
}

void KytV2_CreatePhysicalWorldModel(void)
{
    ensure_thread_info();
    pKytV2_CreatePhysicalWorldModel();
}

uint32_t KytV2_CreateSurfaceAgent(float speed, float waypointTolerance, float lookAheadDistance)
{
    ensure_thread_info();
    return pKytV2_CreateSurfaceAgent(speed, waypointTolerance, lookAheadDistance);
}

uint32_t KytV2_CreateSurfaceNavMesh(float agentRadius, float cellSize, float aggressiveness, int32_t iterations, float targetMaxEdgeLength, int32_t tileSize, float layerHeight, int32_t maxTiles)
{
    ensure_thread_info();
    return pKytV2_CreateSurfaceNavMesh(agentRadius, cellSize, aggressiveness, iterations, targetMaxEdgeLength, tileSize, layerHeight, maxTiles);
}

void * KytV2_CreateSurfaceNavigation(void)
{
    ensure_thread_info();
    return pKytV2_CreateSurfaceNavigation();
}

void KytV2_Destroy(void)
{
    ensure_thread_info();
    pKytV2_Destroy();
}

void KytV2_DestroyAgent(uint32_t agentId)
{
    ensure_thread_info();
    pKytV2_DestroyAgent(agentId);
}

void KytV2_DestroyCover(void)
{
    ensure_thread_info();
    pKytV2_DestroyCover();
}

void KytV2_DestroyFlightAgent(uint32_t agentId)
{
    ensure_thread_info();
    pKytV2_DestroyFlightAgent(agentId);
}

void KytV2_DestroyFlightNavMesh(uint32_t octreeId)
{
    ensure_thread_info();
    pKytV2_DestroyFlightNavMesh(octreeId);
}

void KytV2_DestroyGroundNavigation(void)
{
    ensure_thread_info();
    pKytV2_DestroyGroundNavigation();
}

void KytV2_DestroyNavMesh(void * groundNav, uint32_t navMeshId)
{
    ensure_thread_info();
    pKytV2_DestroyNavMesh(groundNav, navMeshId);
}

void KytV2_DestroyPhysicalWorldModel(void)
{
    ensure_thread_info();
    pKytV2_DestroyPhysicalWorldModel();
}

void KytV2_DestroySurfaceAgent(uint32_t agentId)
{
    ensure_thread_info();
    pKytV2_DestroySurfaceAgent(agentId);
}

void KytV2_DestroySurfaceNavMesh(uint32_t navMeshId)
{
    ensure_thread_info();
    pKytV2_DestroySurfaceNavMesh(navMeshId);
}

void KytV2_DestroySurfaceNavigation(void)
{
    ensure_thread_info();
    pKytV2_DestroySurfaceNavigation();
}

int32_t KytV2_DiagnoseCoverState(uint32_t navMeshId, float centerX, float centerY, float centerZ, float radius, void * outBuffer, int32_t bufferSize)
{
    ensure_thread_info();
    return pKytV2_DiagnoseCoverState(navMeshId, centerX, centerY, centerZ, radius, outBuffer, bufferSize);
}

int32_t KytV2_DoBackgroundWork(void * core)
{
    ensure_thread_info();
    return pKytV2_DoBackgroundWork(core);
}

void KytV2_DumpSurfaceTriangleComparison(uint32_t navMeshId, void * outInputCount, void * outOutputCount)
{
    ensure_thread_info();
    pKytV2_DumpSurfaceTriangleComparison(navMeshId, outInputCount, outOutputCount);
}

int32_t KytV2_FillNavMeshTriangles(void * groundNav, uint32_t navMeshId, void * outTriangles, int32_t maxTriangles)
{
    ensure_thread_info();
    return pKytV2_FillNavMeshTriangles(groundNav, navMeshId, outTriangles, maxTriangles);
}

int32_t KytV2_FindAvoidanceVelocity(void * groundNav, uint32_t navMeshId, float avoiderPosX, float avoiderPosY, float avoiderPosZ, float avoiderRadius, float avoiderHeight, float avoiderWeight, float desiredVelX, float desiredVelY, float desiredVelZ, float maxSpeed, void * obstacles, int32_t obstacleCount, float maxAgentTime, float maxBoundaryTime, float boundaryRange, void * outVelX, void * outVelY, void * outVelZ)
{
    ensure_thread_info();
    return pKytV2_FindAvoidanceVelocity(groundNav, navMeshId, avoiderPosX, avoiderPosY, avoiderPosZ, avoiderRadius, avoiderHeight, avoiderWeight, desiredVelX, desiredVelY, desiredVelZ, maxSpeed, obstacles, obstacleCount, maxAgentTime, maxBoundaryTime, boundaryRange, outVelX, outVelY, outVelZ);
}

int32_t KytV2_FindNearestPoint(void * groundNav, uint32_t navMeshId, float queryX, float queryY, float queryZ, float searchRadius, void * outX, void * outY, void * outZ)
{
    ensure_thread_info();
    return pKytV2_FindNearestPoint(groundNav, navMeshId, queryX, queryY, queryZ, searchRadius, outX, outY, outZ);
}

int32_t KytV2_FindPath(void * groundNav, uint32_t navMeshId, float startX, float startY, float startZ, float endX, float endY, float endZ, float clampRadius, int32_t maxNodes, void * outWaypoints, void * outWaypointCount, int32_t allowPartialResults)
{
    ensure_thread_info();
    return pKytV2_FindPath(groundNav, navMeshId, startX, startY, startZ, endX, endY, endZ, clampRadius, maxNodes, outWaypoints, outWaypointCount, allowPartialResults);
}

int32_t KytV2_FindSurfacePath(uint32_t navMeshId, float startX, float startY, float startZ, float endX, float endY, float endZ, void * outWaypoints, void * outWaypointCount)
{
    ensure_thread_info();
    return pKytV2_FindSurfacePath(navMeshId, startX, startY, startZ, endX, endY, endZ, outWaypoints, outWaypointCount);
}

int32_t KytV2_FlightAgent_GetPath(uint32_t agentId, void * outWaypoints, void * outCount, void * outCurrentIndex)
{
    ensure_thread_info();
    return pKytV2_FlightAgent_GetPath(agentId, outWaypoints, outCount, outCurrentIndex);
}

int32_t KytV2_FlightAgent_RequestPath(uint32_t agentId, uint32_t octreeId, float startX, float startY, float startZ, float endX, float endY, float endZ, int32_t allowPartialResults)
{
    ensure_thread_info();
    return pKytV2_FlightAgent_RequestPath(agentId, octreeId, startX, startY, startZ, endX, endY, endZ, allowPartialResults);
}

void KytV2_FlightAgent_Stop(uint32_t agentId)
{
    ensure_thread_info();
    pKytV2_FlightAgent_Stop(agentId);
}

int32_t KytV2_FlightAgent_Tick(uint32_t agentId, float agentPosX, float agentPosY, float agentPosZ, float deltaTime, void * outMoveData)
{
    ensure_thread_info();
    return pKytV2_FlightAgent_Tick(agentId, agentPosX, agentPosY, agentPosZ, deltaTime, outMoveData);
}

float KytV2_FlightGetGenerationPercentage(uint32_t octreeId)
{
    ensure_thread_info();
    return pKytV2_FlightGetGenerationPercentage(octreeId);
}

int32_t KytV2_FlightHasChangesPending(uint32_t octreeId)
{
    ensure_thread_info();
    return pKytV2_FlightHasChangesPending(octreeId);
}

int32_t KytV2_FlightIsGenerating(uint32_t octreeId)
{
    ensure_thread_info();
    return pKytV2_FlightIsGenerating(octreeId);
}

void KytV2_FlightMarkDirty(uint32_t octreeId, float minX, float minY, float minZ, float maxX, float maxY, float maxZ)
{
    ensure_thread_info();
    pKytV2_FlightMarkDirty(octreeId, minX, minY, minZ, maxX, maxY, maxZ);
}

int32_t KytV2_FlightNavMesh_GetTrianglesAtomic(uint32_t octreeId, int32_t lod, int32_t mode, void * outBuffer)
{
    ensure_thread_info();
    return pKytV2_FlightNavMesh_GetTrianglesAtomic(octreeId, lod, mode, outBuffer);
}

float KytV2_GetGenerationPercentage(void * groundNav, uint32_t navMeshId)
{
    ensure_thread_info();
    return pKytV2_GetGenerationPercentage(groundNav, navMeshId);
}

int32_t KytV2_GetNavMeshTriangleCount(void * groundNav, uint32_t navMeshId)
{
    ensure_thread_info();
    return pKytV2_GetNavMeshTriangleCount(groundNav, navMeshId);
}

int32_t KytV2_GetNavMeshTrianglesAtomic(void * groundNav, uint32_t navMeshId, void * outBuffer)
{
    ensure_thread_info();
    return pKytV2_GetNavMeshTrianglesAtomic(groundNav, navMeshId, outBuffer);
}

int32_t KytV2_GetSurfaceNavMeshTrianglesAtomic(uint32_t navMeshId, void * outBuffer)
{
    ensure_thread_info();
    return pKytV2_GetSurfaceNavMeshTrianglesAtomic(navMeshId, outBuffer);
}

int32_t KytV2_HasChangesPending(void * groundNav, uint32_t navMeshId)
{
    ensure_thread_info();
    return pKytV2_HasChangesPending(groundNav, navMeshId);
}

void KytV2_InitAvoidance(void)
{
    ensure_thread_info();
    pKytV2_InitAvoidance();
}

void KytV2_InitCover(void)
{
    ensure_thread_info();
    pKytV2_InitCover();
}

void KytV2_InitPathPlanner(void)
{
    ensure_thread_info();
    pKytV2_InitPathPlanner();
}

void KytV2_InitSurfacePathPlanner(void)
{
    ensure_thread_info();
    pKytV2_InitSurfacePathPlanner();
}

int32_t KytV2_IsGenerating(void * groundNav, uint32_t navMeshId)
{
    ensure_thread_info();
    return pKytV2_IsGenerating(groundNav, navMeshId);
}

void KytV2_MarkDirty(void * groundNav, uint32_t navMeshId, float minX, float minY, float minZ, float maxX, float maxY, float maxZ)
{
    ensure_thread_info();
    pKytV2_MarkDirty(groundNav, navMeshId, minX, minY, minZ, maxX, maxY, maxZ);
}

void KytV2_Octree_Create(int32_t depth, int32_t blockSize, double cellSize)
{
    ensure_thread_info();
    pKytV2_Octree_Create(depth, blockSize, cellSize);
}

void KytV2_Octree_Destroy(void)
{
    ensure_thread_info();
    pKytV2_Octree_Destroy();
}

int32_t KytV2_Octree_GenerateFromGeometry(void * vertices, int32_t vertexCount, void * indices, int32_t indexCount, double boundsMinX, double boundsMinY, double boundsMinZ, double boundsMaxX, double boundsMaxY, double boundsMaxZ)
{
    ensure_thread_info();
    return pKytV2_Octree_GenerateFromGeometry(vertices, vertexCount, indices, indexCount, boundsMinX, boundsMinY, boundsMinZ, boundsMaxX, boundsMaxY, boundsMaxZ);
}

void KytV2_Octree_GetStats(void * outLeafCount, void * outMemoryBytes, void * outDepth)
{
    ensure_thread_info();
    pKytV2_Octree_GetStats(outLeafCount, outMemoryBytes, outDepth);
}

int32_t KytV2_Octree_GetTriangleCount(int32_t lod)
{
    ensure_thread_info();
    return pKytV2_Octree_GetTriangleCount(lod);
}

int32_t KytV2_Octree_GetTrianglesAtomic(void * outBuffer, int32_t lod, int32_t mode)
{
    ensure_thread_info();
    return pKytV2_Octree_GetTrianglesAtomic(outBuffer, lod, mode);
}

int32_t KytV2_QueryCoverPoints(uint32_t navMeshId, float centerX, float centerY, float centerZ, float radius, uint32_t coverTypeMask, void * outPoints, void * outCount)
{
    ensure_thread_info();
    return pKytV2_QueryCoverPoints(navMeshId, centerX, centerY, centerZ, radius, coverTypeMask, outPoints, outCount);
}

int32_t KytV2_Raycast(void * groundNav, uint32_t navMeshId, float startX, float startY, float startZ, float endX, float endY, float endZ, void * outHitX, void * outHitY, void * outHitZ)
{
    ensure_thread_info();
    return pKytV2_Raycast(groundNav, navMeshId, startX, startY, startZ, endX, endY, endZ, outHitX, outHitY, outHitZ);
}

int32_t KytV2_RemoveTiles(void * groundNav, uint32_t navMeshId, float minX, float minY, float minZ, float maxX, float maxY, float maxZ)
{
    ensure_thread_info();
    return pKytV2_RemoveTiles(groundNav, navMeshId, minX, minY, minZ, maxX, maxY, maxZ);
}

void KytV2_SetGeometry(void * vertices, int32_t vertexDoubleCount, void * indices, int32_t indexCount, float boundsMinX, float boundsMinY, float boundsMinZ, float boundsMaxX, float boundsMaxY, float boundsMaxZ)
{
    ensure_thread_info();
    pKytV2_SetGeometry(vertices, vertexDoubleCount, indices, indexCount, boundsMinX, boundsMinY, boundsMinZ, boundsMaxX, boundsMaxY, boundsMaxZ);
}

void KytV2_SetMaxJobThreads(uint32_t maxThreads)
{
    ensure_thread_info();
    pKytV2_SetMaxJobThreads(maxThreads);
}

void KytV2_SetTestQuad(float centerX, float centerY, float centerZ, float halfSize)
{
    ensure_thread_info();
    pKytV2_SetTestQuad(centerX, centerY, centerZ, halfSize);
}

void KytV2_SetUpdateThread(void * core)
{
    ensure_thread_info();
    pKytV2_SetUpdateThread(core);
}

void KytV2_StartUpdate(void * core, double deltaTimeSeconds)
{
    ensure_thread_info();
    pKytV2_StartUpdate(core, deltaTimeSeconds);
}

int32_t KytV2_SurfaceAgent_RequestPath(uint32_t agentId, uint32_t navMeshId, float startX, float startY, float startZ, float endX, float endY, float endZ)
{
    ensure_thread_info();
    return pKytV2_SurfaceAgent_RequestPath(agentId, navMeshId, startX, startY, startZ, endX, endY, endZ);
}

void KytV2_SurfaceAgent_Stop(uint32_t agentId)
{
    ensure_thread_info();
    pKytV2_SurfaceAgent_Stop(agentId);
}

int32_t KytV2_SurfaceAgent_Tick(uint32_t agentId, float agentPosX, float agentPosY, float agentPosZ, float agentFwdX, float agentFwdY, float agentFwdZ, float agentUpX, float agentUpY, float agentUpZ, float deltaTime, void * outMoveData)
{
    ensure_thread_info();
    return pKytV2_SurfaceAgent_Tick(agentId, agentPosX, agentPosY, agentPosZ, agentFwdX, agentFwdY, agentFwdZ, agentUpX, agentUpY, agentUpZ, deltaTime, outMoveData);
}

float KytV2_SurfaceGetGenerationPercentage(uint32_t navMeshId)
{
    ensure_thread_info();
    return pKytV2_SurfaceGetGenerationPercentage(navMeshId);
}

int32_t KytV2_SurfaceHasChangesPending(uint32_t navMeshId)
{
    ensure_thread_info();
    return pKytV2_SurfaceHasChangesPending(navMeshId);
}

int32_t KytV2_SurfaceIsGenerating(uint32_t navMeshId)
{
    ensure_thread_info();
    return pKytV2_SurfaceIsGenerating(navMeshId);
}

void KytV2_SurfaceMarkDirty(uint32_t navMeshId, float minX, float minY, float minZ, float maxX, float maxY, float maxZ)
{
    ensure_thread_info();
    pKytV2_SurfaceMarkDirty(navMeshId, minX, minY, minZ, maxX, maxY, maxZ);
}

void KytV2_TerminateJobSystem(void)
{
    ensure_thread_info();
    pKytV2_TerminateJobSystem();
}

}
