// Generated by tools/generate_voxels_wrapper.py. Do not edit.
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <mutex>
#include <stdexcept>

#include "dll_loader.h"

struct Vector2 { float x, y; };
struct Vector3 { float x, y, z; };
struct Vector3I { int32_t x, y, z; };

struct AmbientOcclusionArgs {
    float values[7];
};
struct alignas(8) MapSet { uint8_t values[56]; };
struct alignas(8) DetailMapData { uint8_t values[56]; };

static_assert(sizeof(Vector2) == 8);
static_assert(sizeof(Vector3) == 12);
static_assert(sizeof(Vector3I) == 12);
static_assert(sizeof(AmbientOcclusionArgs) == 28);
static_assert(sizeof(MapSet) == 56);
static_assert(sizeof(DetailMapData) == 56);

namespace {
pe_image voxels_image;
std::once_flag voxels_once;
thread_local bool voxels_thread_ready;
void *sysv_assertion_callback;

void WINAPI assertion_bridge(const char *message)
{
    if (sysv_assertion_callback)
        reinterpret_cast<void (*)(const char *)>(sysv_assertion_callback)(message);
}

template<typename T>
uint64_t aggregate_bits(const T &value)
{
    static_assert(sizeof(T) <= sizeof(uint64_t));
    uint64_t result = 0;
    std::memcpy(&result, &value, sizeof(value));
    return result;
}

void initialize(const char *dll_path, const char *sidecar_path);

void ensure_thread_info()
{
    if (!voxels_image.image)
        throw std::runtime_error("Voxels is not initialized; call Init first");
    if (voxels_thread_ready)
        return;
    if (!setup_nt_threadinfo(nullptr))
        std::abort();
    pe_ensure_tls_for_loaded_images();
    voxels_thread_ready = true;
}

using IsoMesher_Calculate_t = void(WINAPI *)(void *, Vector3I *, void *, void *, AmbientOcclusionArgs *);
IsoMesher_Calculate_t pIsoMesher_Calculate;
using IsoMesher_CalculateMaterials_t = void(WINAPI *)(void *, Vector3I *, void *, void *);
IsoMesher_CalculateMaterials_t pIsoMesher_CalculateMaterials;
using IsoMesher_CalculateNormals_t = void(WINAPI *)(void *);
IsoMesher_CalculateNormals_t pIsoMesher_CalculateNormals;
using RegisterAssertionCallback_t = void(WINAPI *)(void *);
RegisterAssertionCallback_t pRegisterAssertionCallback;
using VrDecimatePostprocessing_Create_t = void *(WINAPI *)(void);
VrDecimatePostprocessing_Create_t pVrDecimatePostprocessing_Create;
using VrDecimatePostprocessing_GetClassification_t = void(WINAPI *)(void *, void *, void *, int32_t);
VrDecimatePostprocessing_GetClassification_t pVrDecimatePostprocessing_GetClassification;
using VrDecimatePostprocessing_GetClassificationDetails_t = void(WINAPI *)(void *, int32_t, void *, void *, void *, void *, void *);
VrDecimatePostprocessing_GetClassificationDetails_t pVrDecimatePostprocessing_GetClassificationDetails;
using VrDecimatePostprocessing_GetEdgeThreshold_t = float(WINAPI *)(void *);
VrDecimatePostprocessing_GetEdgeThreshold_t pVrDecimatePostprocessing_GetEdgeThreshold;
using VrDecimatePostprocessing_GetFeatureAngle_t = float(WINAPI *)(void *);
VrDecimatePostprocessing_GetFeatureAngle_t pVrDecimatePostprocessing_GetFeatureAngle;
using VrDecimatePostprocessing_GetIgnoreEdges_t = int32_t(WINAPI *)(void *);
VrDecimatePostprocessing_GetIgnoreEdges_t pVrDecimatePostprocessing_GetIgnoreEdges;
using VrDecimatePostprocessing_GetInMemorySize_t = uint64_t(WINAPI *)(void *);
VrDecimatePostprocessing_GetInMemorySize_t pVrDecimatePostprocessing_GetInMemorySize;
using VrDecimatePostprocessing_GetPlaneThreshold_t = float(WINAPI *)(void *);
VrDecimatePostprocessing_GetPlaneThreshold_t pVrDecimatePostprocessing_GetPlaneThreshold;
using VrDecimatePostprocessing_Release_t = void(WINAPI *)(void *);
VrDecimatePostprocessing_Release_t pVrDecimatePostprocessing_Release;
using VrDecimatePostprocessing_SetEdgeThreshold_t = void(WINAPI *)(void *, float);
VrDecimatePostprocessing_SetEdgeThreshold_t pVrDecimatePostprocessing_SetEdgeThreshold;
using VrDecimatePostprocessing_SetFeatureAngle_t = void(WINAPI *)(void *, float);
VrDecimatePostprocessing_SetFeatureAngle_t pVrDecimatePostprocessing_SetFeatureAngle;
using VrDecimatePostprocessing_SetIgnoreEdges_t = void(WINAPI *)(void *, int32_t);
VrDecimatePostprocessing_SetIgnoreEdges_t pVrDecimatePostprocessing_SetIgnoreEdges;
using VrDecimatePostprocessing_SetPlaneThreshold_t = void(WINAPI *)(void *, float);
VrDecimatePostprocessing_SetPlaneThreshold_t pVrDecimatePostprocessing_SetPlaneThreshold;
using VrDecimatePostprocessing_Simplify_t = int32_t(WINAPI *)(void *, int32_t);
VrDecimatePostprocessing_Simplify_t pVrDecimatePostprocessing_Simplify;
using VrDecimatePostprocessing_TrySimplify_t = int32_t(WINAPI *)(void *, int32_t, void *, void *, void *);
VrDecimatePostprocessing_TrySimplify_t pVrDecimatePostprocessing_TrySimplify;
using VrPlanetShape_CheckContentRange_t = int32_t(WINAPI *)(void *, Vector3I *, Vector3I *, float, int32_t);
VrPlanetShape_CheckContentRange_t pVrPlanetShape_CheckContentRange;
using VrPlanetShape_Create_t = void *(WINAPI *)(Vector3 *, float, float, float, MapSet *, DetailMapData *, int32_t);
VrPlanetShape_Create_t pVrPlanetShape_Create;
using VrPlanetShape_GetHeight_t = float(WINAPI *)(void *, uint64_t, int32_t, void *);
VrPlanetShape_GetHeight_t pVrPlanetShape_GetHeight;
using VrPlanetShape_GetInMemorySize_t = uint64_t(WINAPI *)(void *);
VrPlanetShape_GetInMemorySize_t pVrPlanetShape_GetInMemorySize;
using VrPlanetShape_GetValue_t = float(WINAPI *)(void *, uint64_t, int32_t, void *);
VrPlanetShape_GetValue_t pVrPlanetShape_GetValue;
using VrPlanetShape_ReadContentRange_t = void(WINAPI *)(void *, void *, int32_t, int32_t, Vector3I *, Vector3I *, Vector3I *, float, int32_t);
VrPlanetShape_ReadContentRange_t pVrPlanetShape_ReadContentRange;
using VrPlanetShape_Release_t = void(WINAPI *)(void *);
VrPlanetShape_Release_t pVrPlanetShape_Release;
using VrPostprocessing_Process_t = void(WINAPI *)(void *, void *);
VrPostprocessing_Process_t pVrPostprocessing_Process;
using VrRandomizePostprocessing_Create_t = void *(WINAPI *)(float);
VrRandomizePostprocessing_Create_t pVrRandomizePostprocessing_Create;
using VrRandomizePostprocessing_GetInMemorySize_t = uint64_t(WINAPI *)(void *);
VrRandomizePostprocessing_GetInMemorySize_t pVrRandomizePostprocessing_GetInMemorySize;
using VrRandomizePostprocessing_Release_t = void(WINAPI *)(void *);
VrRandomizePostprocessing_Release_t pVrRandomizePostprocessing_Release;
using VrSewGuide_Create1_t = void *(WINAPI *)(int32_t, Vector3I *, Vector3I *, void *);
VrSewGuide_Create1_t pVrSewGuide_Create1;
using VrSewGuide_Create2_t = void *(WINAPI *)(void *, void *);
VrSewGuide_Create2_t pVrSewGuide_Create2;
using VrSewGuide_GetEnd_t = void(WINAPI *)(Vector3I *, void *);
VrSewGuide_GetEnd_t pVrSewGuide_GetEnd;
using VrSewGuide_GetInMemorySize_t = uint64_t(WINAPI *)(void *);
VrSewGuide_GetInMemorySize_t pVrSewGuide_GetInMemorySize;
using VrSewGuide_GetLod_t = int32_t(WINAPI *)(void *);
VrSewGuide_GetLod_t pVrSewGuide_GetLod;
using VrSewGuide_GetMesh_t = void *(WINAPI *)(void *);
VrSewGuide_GetMesh_t pVrSewGuide_GetMesh;
using VrSewGuide_GetScale_t = float(WINAPI *)(void *);
VrSewGuide_GetScale_t pVrSewGuide_GetScale;
using VrSewGuide_GetSewn_t = int32_t(WINAPI *)(void *);
VrSewGuide_GetSewn_t pVrSewGuide_GetSewn;
using VrSewGuide_GetSize_t = void(WINAPI *)(Vector3I *, void *);
VrSewGuide_GetSize_t pVrSewGuide_GetSize;
using VrSewGuide_GetStart_t = void(WINAPI *)(Vector3I *, void *);
VrSewGuide_GetStart_t pVrSewGuide_GetStart;
using VrSewGuide_GetVersion_t = int32_t(WINAPI *)(void *);
VrSewGuide_GetVersion_t pVrSewGuide_GetVersion;
using VrSewGuide_InvalidateGenerated_t = void(WINAPI *)(void *, Vector3I *);
VrSewGuide_InvalidateGenerated_t pVrSewGuide_InvalidateGenerated;
using VrSewGuide_Recycle1_t = void(WINAPI *)(void *, int32_t, Vector3I *, Vector3I *, void *);
VrSewGuide_Recycle1_t pVrSewGuide_Recycle1;
using VrSewGuide_Recycle2_t = void(WINAPI *)(void *, void *, void *);
VrSewGuide_Recycle2_t pVrSewGuide_Recycle2;
using VrSewGuide_Release_t = void(WINAPI *)(void *);
VrSewGuide_Release_t pVrSewGuide_Release;
using VrSewGuide_Reset_t = void(WINAPI *)(void *);
VrSewGuide_Reset_t pVrSewGuide_Reset;
using VrSewGuide_SetMesh_t = void(WINAPI *)(void *, void *, void *);
VrSewGuide_SetMesh_t pVrSewGuide_SetMesh;
using VrShellDataCache_Empty_t = void *(WINAPI *)(void);
VrShellDataCache_Empty_t pVrShellDataCache_Empty;
using VrShellDataCache_FromDataCube_t = void *(WINAPI *)(Vector3I *, void *, void *);
VrShellDataCache_FromDataCube_t pVrShellDataCache_FromDataCube;
using VrShellDataCache_Full_t = void *(WINAPI *)(void);
VrShellDataCache_Full_t pVrShellDataCache_Full;
using VrShellDataCache_GetInMemorySize_t = uint64_t(WINAPI *)(void *);
VrShellDataCache_GetInMemorySize_t pVrShellDataCache_GetInMemorySize;
using VrShellDataCache_Release_t = void(WINAPI *)(void *);
VrShellDataCache_Release_t pVrShellDataCache_Release;
using VrTailor_ClearBuffers_t = void(WINAPI *)(void *);
VrTailor_ClearBuffers_t pVrTailor_ClearBuffers;
using VrTailor_Create_t = void *(WINAPI *)(void);
VrTailor_Create_t pVrTailor_Create;
using VrTailor_DebugReadGenerated_t = void(WINAPI *)(void *, void *, void *);
VrTailor_DebugReadGenerated_t pVrTailor_DebugReadGenerated;
using VrTailor_DebugReadRemapped_t = void(WINAPI *)(void *, void *, void *);
VrTailor_DebugReadRemapped_t pVrTailor_DebugReadRemapped;
using VrTailor_DebugReadStudied_t = void(WINAPI *)(void *, void *, void *);
VrTailor_DebugReadStudied_t pVrTailor_DebugReadStudied;
using VrTailor_GetInMemorySize_t = uint64_t(WINAPI *)(void *);
VrTailor_GetInMemorySize_t pVrTailor_GetInMemorySize;
using VrTailor_RecalculateEdgeNormal_t = void(WINAPI *)(void *, void *);
VrTailor_RecalculateEdgeNormal_t pVrTailor_RecalculateEdgeNormal;
using VrTailor_Release_t = void(WINAPI *)(void *);
VrTailor_Release_t pVrTailor_Release;
using VrTailor_SetDebug_t = void(WINAPI *)(void *, int32_t);
VrTailor_SetDebug_t pVrTailor_SetDebug;
using VrTailor_SetGenerate_t = void(WINAPI *)(void *, uint8_t);
VrTailor_SetGenerate_t pVrTailor_SetGenerate;
using VrTailor_Sew_t = void(WINAPI *)(void *, void *, uint8_t, Vector3I *, Vector3I *);
VrTailor_Sew_t pVrTailor_Sew;
using VrVoxelMesh_Clear_t = void(WINAPI *)(void *);
VrVoxelMesh_Clear_t pVrVoxelMesh_Clear;
using VrVoxelMesh_Create_t = void *(WINAPI *)(Vector3I *, Vector3I *, int32_t);
VrVoxelMesh_Create_t pVrVoxelMesh_Create;
using VrVoxelMesh_GetEnd_t = void(WINAPI *)(Vector3I *, void *);
VrVoxelMesh_GetEnd_t pVrVoxelMesh_GetEnd;
using VrVoxelMesh_GetInMemorySize_t = uint64_t(WINAPI *)(void *);
VrVoxelMesh_GetInMemorySize_t pVrVoxelMesh_GetInMemorySize;
using VrVoxelMesh_GetLod_t = int32_t(WINAPI *)(void *);
VrVoxelMesh_GetLod_t pVrVoxelMesh_GetLod;
using VrVoxelMesh_GetMeshData_t = void(WINAPI *)(void *, void *, void *, void *, void *, void *, void *);
VrVoxelMesh_GetMeshData_t pVrVoxelMesh_GetMeshData;
using VrVoxelMesh_GetScale_t = float(WINAPI *)(void *);
VrVoxelMesh_GetScale_t pVrVoxelMesh_GetScale;
using VrVoxelMesh_GetStart_t = void(WINAPI *)(Vector3I *, void *);
VrVoxelMesh_GetStart_t pVrVoxelMesh_GetStart;
using VrVoxelMesh_GetTriangleCount_t = int32_t(WINAPI *)(void *);
VrVoxelMesh_GetTriangleCount_t pVrVoxelMesh_GetTriangleCount;
using VrVoxelMesh_GetTriangles_t = void *(WINAPI *)(void *);
VrVoxelMesh_GetTriangles_t pVrVoxelMesh_GetTriangles;
using VrVoxelMesh_GetVertexCount_t = int32_t(WINAPI *)(void *);
VrVoxelMesh_GetVertexCount_t pVrVoxelMesh_GetVertexCount;
using VrVoxelMesh_GetVertices_t = void *(WINAPI *)(void *);
VrVoxelMesh_GetVertices_t pVrVoxelMesh_GetVertices;
using VrVoxelMesh_Recycle_t = void(WINAPI *)(void *, Vector3I *, Vector3I *, int32_t);
VrVoxelMesh_Recycle_t pVrVoxelMesh_Recycle;
using VrVoxelMesh_Release_t = void(WINAPI *)(void *);
VrVoxelMesh_Release_t pVrVoxelMesh_Release;

void initialize(const char *dll_path, const char *sidecar_path)
{
    if (!dll_path)
        throw std::invalid_argument("Voxels Init requires a DLL path");
    std::call_once(voxels_once, [dll_path, sidecar_path] {
        if (!load_dll(&voxels_image, dll_path, sidecar_path))
            throw std::runtime_error("Failed to load VRage.Voxels.Native.dll");
        pIsoMesher_Calculate = reinterpret_cast<IsoMesher_Calculate_t>(get_export("IsoMesher_Calculate"));
        if (!pIsoMesher_Calculate)
            throw std::runtime_error("Missing Voxels export: IsoMesher_Calculate");
        pIsoMesher_CalculateMaterials = reinterpret_cast<IsoMesher_CalculateMaterials_t>(get_export("IsoMesher_CalculateMaterials"));
        if (!pIsoMesher_CalculateMaterials)
            throw std::runtime_error("Missing Voxels export: IsoMesher_CalculateMaterials");
        pIsoMesher_CalculateNormals = reinterpret_cast<IsoMesher_CalculateNormals_t>(get_export("IsoMesher_CalculateNormals"));
        if (!pIsoMesher_CalculateNormals)
            throw std::runtime_error("Missing Voxels export: IsoMesher_CalculateNormals");
        pRegisterAssertionCallback = reinterpret_cast<RegisterAssertionCallback_t>(get_export("RegisterAssertionCallback"));
        if (!pRegisterAssertionCallback)
            throw std::runtime_error("Missing Voxels export: RegisterAssertionCallback");
        pVrDecimatePostprocessing_Create = reinterpret_cast<VrDecimatePostprocessing_Create_t>(get_export("VrDecimatePostprocessing_Create"));
        if (!pVrDecimatePostprocessing_Create)
            throw std::runtime_error("Missing Voxels export: VrDecimatePostprocessing_Create");
        pVrDecimatePostprocessing_GetClassification = reinterpret_cast<VrDecimatePostprocessing_GetClassification_t>(get_export("VrDecimatePostprocessing_GetClassification"));
        if (!pVrDecimatePostprocessing_GetClassification)
            throw std::runtime_error("Missing Voxels export: VrDecimatePostprocessing_GetClassification");
        pVrDecimatePostprocessing_GetClassificationDetails = reinterpret_cast<VrDecimatePostprocessing_GetClassificationDetails_t>(get_export("VrDecimatePostprocessing_GetClassificationDetails"));
        if (!pVrDecimatePostprocessing_GetClassificationDetails)
            throw std::runtime_error("Missing Voxels export: VrDecimatePostprocessing_GetClassificationDetails");
        pVrDecimatePostprocessing_GetEdgeThreshold = reinterpret_cast<VrDecimatePostprocessing_GetEdgeThreshold_t>(get_export("VrDecimatePostprocessing_GetEdgeThreshold"));
        if (!pVrDecimatePostprocessing_GetEdgeThreshold)
            throw std::runtime_error("Missing Voxels export: VrDecimatePostprocessing_GetEdgeThreshold");
        pVrDecimatePostprocessing_GetFeatureAngle = reinterpret_cast<VrDecimatePostprocessing_GetFeatureAngle_t>(get_export("VrDecimatePostprocessing_GetFeatureAngle"));
        if (!pVrDecimatePostprocessing_GetFeatureAngle)
            throw std::runtime_error("Missing Voxels export: VrDecimatePostprocessing_GetFeatureAngle");
        pVrDecimatePostprocessing_GetIgnoreEdges = reinterpret_cast<VrDecimatePostprocessing_GetIgnoreEdges_t>(get_export("VrDecimatePostprocessing_GetIgnoreEdges"));
        if (!pVrDecimatePostprocessing_GetIgnoreEdges)
            throw std::runtime_error("Missing Voxels export: VrDecimatePostprocessing_GetIgnoreEdges");
        pVrDecimatePostprocessing_GetInMemorySize = reinterpret_cast<VrDecimatePostprocessing_GetInMemorySize_t>(get_export("VrDecimatePostprocessing_GetInMemorySize"));
        if (!pVrDecimatePostprocessing_GetInMemorySize)
            throw std::runtime_error("Missing Voxels export: VrDecimatePostprocessing_GetInMemorySize");
        pVrDecimatePostprocessing_GetPlaneThreshold = reinterpret_cast<VrDecimatePostprocessing_GetPlaneThreshold_t>(get_export("VrDecimatePostprocessing_GetPlaneThreshold"));
        if (!pVrDecimatePostprocessing_GetPlaneThreshold)
            throw std::runtime_error("Missing Voxels export: VrDecimatePostprocessing_GetPlaneThreshold");
        pVrDecimatePostprocessing_Release = reinterpret_cast<VrDecimatePostprocessing_Release_t>(get_export("VrDecimatePostprocessing_Release"));
        if (!pVrDecimatePostprocessing_Release)
            throw std::runtime_error("Missing Voxels export: VrDecimatePostprocessing_Release");
        pVrDecimatePostprocessing_SetEdgeThreshold = reinterpret_cast<VrDecimatePostprocessing_SetEdgeThreshold_t>(get_export("VrDecimatePostprocessing_SetEdgeThreshold"));
        if (!pVrDecimatePostprocessing_SetEdgeThreshold)
            throw std::runtime_error("Missing Voxels export: VrDecimatePostprocessing_SetEdgeThreshold");
        pVrDecimatePostprocessing_SetFeatureAngle = reinterpret_cast<VrDecimatePostprocessing_SetFeatureAngle_t>(get_export("VrDecimatePostprocessing_SetFeatureAngle"));
        if (!pVrDecimatePostprocessing_SetFeatureAngle)
            throw std::runtime_error("Missing Voxels export: VrDecimatePostprocessing_SetFeatureAngle");
        pVrDecimatePostprocessing_SetIgnoreEdges = reinterpret_cast<VrDecimatePostprocessing_SetIgnoreEdges_t>(get_export("VrDecimatePostprocessing_SetIgnoreEdges"));
        if (!pVrDecimatePostprocessing_SetIgnoreEdges)
            throw std::runtime_error("Missing Voxels export: VrDecimatePostprocessing_SetIgnoreEdges");
        pVrDecimatePostprocessing_SetPlaneThreshold = reinterpret_cast<VrDecimatePostprocessing_SetPlaneThreshold_t>(get_export("VrDecimatePostprocessing_SetPlaneThreshold"));
        if (!pVrDecimatePostprocessing_SetPlaneThreshold)
            throw std::runtime_error("Missing Voxels export: VrDecimatePostprocessing_SetPlaneThreshold");
        pVrDecimatePostprocessing_Simplify = reinterpret_cast<VrDecimatePostprocessing_Simplify_t>(get_export("VrDecimatePostprocessing_Simplify"));
        if (!pVrDecimatePostprocessing_Simplify)
            throw std::runtime_error("Missing Voxels export: VrDecimatePostprocessing_Simplify");
        pVrDecimatePostprocessing_TrySimplify = reinterpret_cast<VrDecimatePostprocessing_TrySimplify_t>(get_export("VrDecimatePostprocessing_TrySimplify"));
        if (!pVrDecimatePostprocessing_TrySimplify)
            throw std::runtime_error("Missing Voxels export: VrDecimatePostprocessing_TrySimplify");
        pVrPlanetShape_CheckContentRange = reinterpret_cast<VrPlanetShape_CheckContentRange_t>(get_export("VrPlanetShape_CheckContentRange"));
        if (!pVrPlanetShape_CheckContentRange)
            throw std::runtime_error("Missing Voxels export: VrPlanetShape_CheckContentRange");
        pVrPlanetShape_Create = reinterpret_cast<VrPlanetShape_Create_t>(get_export("VrPlanetShape_Create"));
        if (!pVrPlanetShape_Create)
            throw std::runtime_error("Missing Voxels export: VrPlanetShape_Create");
        pVrPlanetShape_GetHeight = reinterpret_cast<VrPlanetShape_GetHeight_t>(get_export("VrPlanetShape_GetHeight"));
        if (!pVrPlanetShape_GetHeight)
            throw std::runtime_error("Missing Voxels export: VrPlanetShape_GetHeight");
        pVrPlanetShape_GetInMemorySize = reinterpret_cast<VrPlanetShape_GetInMemorySize_t>(get_export("VrPlanetShape_GetInMemorySize"));
        if (!pVrPlanetShape_GetInMemorySize)
            throw std::runtime_error("Missing Voxels export: VrPlanetShape_GetInMemorySize");
        pVrPlanetShape_GetValue = reinterpret_cast<VrPlanetShape_GetValue_t>(get_export("VrPlanetShape_GetValue"));
        if (!pVrPlanetShape_GetValue)
            throw std::runtime_error("Missing Voxels export: VrPlanetShape_GetValue");
        pVrPlanetShape_ReadContentRange = reinterpret_cast<VrPlanetShape_ReadContentRange_t>(get_export("VrPlanetShape_ReadContentRange"));
        if (!pVrPlanetShape_ReadContentRange)
            throw std::runtime_error("Missing Voxels export: VrPlanetShape_ReadContentRange");
        pVrPlanetShape_Release = reinterpret_cast<VrPlanetShape_Release_t>(get_export("VrPlanetShape_Release"));
        if (!pVrPlanetShape_Release)
            throw std::runtime_error("Missing Voxels export: VrPlanetShape_Release");
        pVrPostprocessing_Process = reinterpret_cast<VrPostprocessing_Process_t>(get_export("VrPostprocessing_Process"));
        if (!pVrPostprocessing_Process)
            throw std::runtime_error("Missing Voxels export: VrPostprocessing_Process");
        pVrRandomizePostprocessing_Create = reinterpret_cast<VrRandomizePostprocessing_Create_t>(get_export("VrRandomizePostprocessing_Create"));
        if (!pVrRandomizePostprocessing_Create)
            throw std::runtime_error("Missing Voxels export: VrRandomizePostprocessing_Create");
        pVrRandomizePostprocessing_GetInMemorySize = reinterpret_cast<VrRandomizePostprocessing_GetInMemorySize_t>(get_export("VrRandomizePostprocessing_GetInMemorySize"));
        if (!pVrRandomizePostprocessing_GetInMemorySize)
            throw std::runtime_error("Missing Voxels export: VrRandomizePostprocessing_GetInMemorySize");
        pVrRandomizePostprocessing_Release = reinterpret_cast<VrRandomizePostprocessing_Release_t>(get_export("VrRandomizePostprocessing_Release"));
        if (!pVrRandomizePostprocessing_Release)
            throw std::runtime_error("Missing Voxels export: VrRandomizePostprocessing_Release");
        pVrSewGuide_Create1 = reinterpret_cast<VrSewGuide_Create1_t>(get_export("VrSewGuide_Create1"));
        if (!pVrSewGuide_Create1)
            throw std::runtime_error("Missing Voxels export: VrSewGuide_Create1");
        pVrSewGuide_Create2 = reinterpret_cast<VrSewGuide_Create2_t>(get_export("VrSewGuide_Create2"));
        if (!pVrSewGuide_Create2)
            throw std::runtime_error("Missing Voxels export: VrSewGuide_Create2");
        pVrSewGuide_GetEnd = reinterpret_cast<VrSewGuide_GetEnd_t>(get_export("VrSewGuide_GetEnd"));
        if (!pVrSewGuide_GetEnd)
            throw std::runtime_error("Missing Voxels export: VrSewGuide_GetEnd");
        pVrSewGuide_GetInMemorySize = reinterpret_cast<VrSewGuide_GetInMemorySize_t>(get_export("VrSewGuide_GetInMemorySize"));
        if (!pVrSewGuide_GetInMemorySize)
            throw std::runtime_error("Missing Voxels export: VrSewGuide_GetInMemorySize");
        pVrSewGuide_GetLod = reinterpret_cast<VrSewGuide_GetLod_t>(get_export("VrSewGuide_GetLod"));
        if (!pVrSewGuide_GetLod)
            throw std::runtime_error("Missing Voxels export: VrSewGuide_GetLod");
        pVrSewGuide_GetMesh = reinterpret_cast<VrSewGuide_GetMesh_t>(get_export("VrSewGuide_GetMesh"));
        if (!pVrSewGuide_GetMesh)
            throw std::runtime_error("Missing Voxels export: VrSewGuide_GetMesh");
        pVrSewGuide_GetScale = reinterpret_cast<VrSewGuide_GetScale_t>(get_export("VrSewGuide_GetScale"));
        if (!pVrSewGuide_GetScale)
            throw std::runtime_error("Missing Voxels export: VrSewGuide_GetScale");
        pVrSewGuide_GetSewn = reinterpret_cast<VrSewGuide_GetSewn_t>(get_export("VrSewGuide_GetSewn"));
        if (!pVrSewGuide_GetSewn)
            throw std::runtime_error("Missing Voxels export: VrSewGuide_GetSewn");
        pVrSewGuide_GetSize = reinterpret_cast<VrSewGuide_GetSize_t>(get_export("VrSewGuide_GetSize"));
        if (!pVrSewGuide_GetSize)
            throw std::runtime_error("Missing Voxels export: VrSewGuide_GetSize");
        pVrSewGuide_GetStart = reinterpret_cast<VrSewGuide_GetStart_t>(get_export("VrSewGuide_GetStart"));
        if (!pVrSewGuide_GetStart)
            throw std::runtime_error("Missing Voxels export: VrSewGuide_GetStart");
        pVrSewGuide_GetVersion = reinterpret_cast<VrSewGuide_GetVersion_t>(get_export("VrSewGuide_GetVersion"));
        if (!pVrSewGuide_GetVersion)
            throw std::runtime_error("Missing Voxels export: VrSewGuide_GetVersion");
        pVrSewGuide_InvalidateGenerated = reinterpret_cast<VrSewGuide_InvalidateGenerated_t>(get_export("VrSewGuide_InvalidateGenerated"));
        if (!pVrSewGuide_InvalidateGenerated)
            throw std::runtime_error("Missing Voxels export: VrSewGuide_InvalidateGenerated");
        pVrSewGuide_Recycle1 = reinterpret_cast<VrSewGuide_Recycle1_t>(get_export("VrSewGuide_Recycle1"));
        if (!pVrSewGuide_Recycle1)
            throw std::runtime_error("Missing Voxels export: VrSewGuide_Recycle1");
        pVrSewGuide_Recycle2 = reinterpret_cast<VrSewGuide_Recycle2_t>(get_export("VrSewGuide_Recycle2"));
        if (!pVrSewGuide_Recycle2)
            throw std::runtime_error("Missing Voxels export: VrSewGuide_Recycle2");
        pVrSewGuide_Release = reinterpret_cast<VrSewGuide_Release_t>(get_export("VrSewGuide_Release"));
        if (!pVrSewGuide_Release)
            throw std::runtime_error("Missing Voxels export: VrSewGuide_Release");
        pVrSewGuide_Reset = reinterpret_cast<VrSewGuide_Reset_t>(get_export("VrSewGuide_Reset"));
        if (!pVrSewGuide_Reset)
            throw std::runtime_error("Missing Voxels export: VrSewGuide_Reset");
        pVrSewGuide_SetMesh = reinterpret_cast<VrSewGuide_SetMesh_t>(get_export("VrSewGuide_SetMesh"));
        if (!pVrSewGuide_SetMesh)
            throw std::runtime_error("Missing Voxels export: VrSewGuide_SetMesh");
        pVrShellDataCache_Empty = reinterpret_cast<VrShellDataCache_Empty_t>(get_export("VrShellDataCache_Empty"));
        if (!pVrShellDataCache_Empty)
            throw std::runtime_error("Missing Voxels export: VrShellDataCache_Empty");
        pVrShellDataCache_FromDataCube = reinterpret_cast<VrShellDataCache_FromDataCube_t>(get_export("VrShellDataCache_FromDataCube"));
        if (!pVrShellDataCache_FromDataCube)
            throw std::runtime_error("Missing Voxels export: VrShellDataCache_FromDataCube");
        pVrShellDataCache_Full = reinterpret_cast<VrShellDataCache_Full_t>(get_export("VrShellDataCache_Full"));
        if (!pVrShellDataCache_Full)
            throw std::runtime_error("Missing Voxels export: VrShellDataCache_Full");
        pVrShellDataCache_GetInMemorySize = reinterpret_cast<VrShellDataCache_GetInMemorySize_t>(get_export("VrShellDataCache_GetInMemorySize"));
        if (!pVrShellDataCache_GetInMemorySize)
            throw std::runtime_error("Missing Voxels export: VrShellDataCache_GetInMemorySize");
        pVrShellDataCache_Release = reinterpret_cast<VrShellDataCache_Release_t>(get_export("VrShellDataCache_Release"));
        if (!pVrShellDataCache_Release)
            throw std::runtime_error("Missing Voxels export: VrShellDataCache_Release");
        pVrTailor_ClearBuffers = reinterpret_cast<VrTailor_ClearBuffers_t>(get_export("VrTailor_ClearBuffers"));
        if (!pVrTailor_ClearBuffers)
            throw std::runtime_error("Missing Voxels export: VrTailor_ClearBuffers");
        pVrTailor_Create = reinterpret_cast<VrTailor_Create_t>(get_export("VrTailor_Create"));
        if (!pVrTailor_Create)
            throw std::runtime_error("Missing Voxels export: VrTailor_Create");
        pVrTailor_DebugReadGenerated = reinterpret_cast<VrTailor_DebugReadGenerated_t>(get_export("VrTailor_DebugReadGenerated"));
        if (!pVrTailor_DebugReadGenerated)
            throw std::runtime_error("Missing Voxels export: VrTailor_DebugReadGenerated");
        pVrTailor_DebugReadRemapped = reinterpret_cast<VrTailor_DebugReadRemapped_t>(get_export("VrTailor_DebugReadRemapped"));
        if (!pVrTailor_DebugReadRemapped)
            throw std::runtime_error("Missing Voxels export: VrTailor_DebugReadRemapped");
        pVrTailor_DebugReadStudied = reinterpret_cast<VrTailor_DebugReadStudied_t>(get_export("VrTailor_DebugReadStudied"));
        if (!pVrTailor_DebugReadStudied)
            throw std::runtime_error("Missing Voxels export: VrTailor_DebugReadStudied");
        pVrTailor_GetInMemorySize = reinterpret_cast<VrTailor_GetInMemorySize_t>(get_export("VrTailor_GetInMemorySize"));
        if (!pVrTailor_GetInMemorySize)
            throw std::runtime_error("Missing Voxels export: VrTailor_GetInMemorySize");
        pVrTailor_RecalculateEdgeNormal = reinterpret_cast<VrTailor_RecalculateEdgeNormal_t>(get_export("VrTailor_RecalculateEdgeNormal"));
        if (!pVrTailor_RecalculateEdgeNormal)
            throw std::runtime_error("Missing Voxels export: VrTailor_RecalculateEdgeNormal");
        pVrTailor_Release = reinterpret_cast<VrTailor_Release_t>(get_export("VrTailor_Release"));
        if (!pVrTailor_Release)
            throw std::runtime_error("Missing Voxels export: VrTailor_Release");
        pVrTailor_SetDebug = reinterpret_cast<VrTailor_SetDebug_t>(get_export("VrTailor_SetDebug"));
        if (!pVrTailor_SetDebug)
            throw std::runtime_error("Missing Voxels export: VrTailor_SetDebug");
        pVrTailor_SetGenerate = reinterpret_cast<VrTailor_SetGenerate_t>(get_export("VrTailor_SetGenerate"));
        if (!pVrTailor_SetGenerate)
            throw std::runtime_error("Missing Voxels export: VrTailor_SetGenerate");
        pVrTailor_Sew = reinterpret_cast<VrTailor_Sew_t>(get_export("VrTailor_Sew"));
        if (!pVrTailor_Sew)
            throw std::runtime_error("Missing Voxels export: VrTailor_Sew");
        pVrVoxelMesh_Clear = reinterpret_cast<VrVoxelMesh_Clear_t>(get_export("VrVoxelMesh_Clear"));
        if (!pVrVoxelMesh_Clear)
            throw std::runtime_error("Missing Voxels export: VrVoxelMesh_Clear");
        pVrVoxelMesh_Create = reinterpret_cast<VrVoxelMesh_Create_t>(get_export("VrVoxelMesh_Create"));
        if (!pVrVoxelMesh_Create)
            throw std::runtime_error("Missing Voxels export: VrVoxelMesh_Create");
        pVrVoxelMesh_GetEnd = reinterpret_cast<VrVoxelMesh_GetEnd_t>(get_export("VrVoxelMesh_GetEnd"));
        if (!pVrVoxelMesh_GetEnd)
            throw std::runtime_error("Missing Voxels export: VrVoxelMesh_GetEnd");
        pVrVoxelMesh_GetInMemorySize = reinterpret_cast<VrVoxelMesh_GetInMemorySize_t>(get_export("VrVoxelMesh_GetInMemorySize"));
        if (!pVrVoxelMesh_GetInMemorySize)
            throw std::runtime_error("Missing Voxels export: VrVoxelMesh_GetInMemorySize");
        pVrVoxelMesh_GetLod = reinterpret_cast<VrVoxelMesh_GetLod_t>(get_export("VrVoxelMesh_GetLod"));
        if (!pVrVoxelMesh_GetLod)
            throw std::runtime_error("Missing Voxels export: VrVoxelMesh_GetLod");
        pVrVoxelMesh_GetMeshData = reinterpret_cast<VrVoxelMesh_GetMeshData_t>(get_export("VrVoxelMesh_GetMeshData"));
        if (!pVrVoxelMesh_GetMeshData)
            throw std::runtime_error("Missing Voxels export: VrVoxelMesh_GetMeshData");
        pVrVoxelMesh_GetScale = reinterpret_cast<VrVoxelMesh_GetScale_t>(get_export("VrVoxelMesh_GetScale"));
        if (!pVrVoxelMesh_GetScale)
            throw std::runtime_error("Missing Voxels export: VrVoxelMesh_GetScale");
        pVrVoxelMesh_GetStart = reinterpret_cast<VrVoxelMesh_GetStart_t>(get_export("VrVoxelMesh_GetStart"));
        if (!pVrVoxelMesh_GetStart)
            throw std::runtime_error("Missing Voxels export: VrVoxelMesh_GetStart");
        pVrVoxelMesh_GetTriangleCount = reinterpret_cast<VrVoxelMesh_GetTriangleCount_t>(get_export("VrVoxelMesh_GetTriangleCount"));
        if (!pVrVoxelMesh_GetTriangleCount)
            throw std::runtime_error("Missing Voxels export: VrVoxelMesh_GetTriangleCount");
        pVrVoxelMesh_GetTriangles = reinterpret_cast<VrVoxelMesh_GetTriangles_t>(get_export("VrVoxelMesh_GetTriangles"));
        if (!pVrVoxelMesh_GetTriangles)
            throw std::runtime_error("Missing Voxels export: VrVoxelMesh_GetTriangles");
        pVrVoxelMesh_GetVertexCount = reinterpret_cast<VrVoxelMesh_GetVertexCount_t>(get_export("VrVoxelMesh_GetVertexCount"));
        if (!pVrVoxelMesh_GetVertexCount)
            throw std::runtime_error("Missing Voxels export: VrVoxelMesh_GetVertexCount");
        pVrVoxelMesh_GetVertices = reinterpret_cast<VrVoxelMesh_GetVertices_t>(get_export("VrVoxelMesh_GetVertices"));
        if (!pVrVoxelMesh_GetVertices)
            throw std::runtime_error("Missing Voxels export: VrVoxelMesh_GetVertices");
        pVrVoxelMesh_Recycle = reinterpret_cast<VrVoxelMesh_Recycle_t>(get_export("VrVoxelMesh_Recycle"));
        if (!pVrVoxelMesh_Recycle)
            throw std::runtime_error("Missing Voxels export: VrVoxelMesh_Recycle");
        pVrVoxelMesh_Release = reinterpret_cast<VrVoxelMesh_Release_t>(get_export("VrVoxelMesh_Release"));
        if (!pVrVoxelMesh_Release)
            throw std::runtime_error("Missing Voxels export: VrVoxelMesh_Release");
    });
}
}

extern "C" {

void Init(const char *dll_path, const char *sidecar_path)
{
    initialize(dll_path, sidecar_path);
}

void IsoMesher_Calculate(void * mesh, Vector3I numSamples, void * content, void * material, AmbientOcclusionArgs aoArgs)
{
    ensure_thread_info();
    alignas(16) Vector3I numSamples_pe = numSamples;
    alignas(16) AmbientOcclusionArgs aoArgs_pe = aoArgs;
    pIsoMesher_Calculate(mesh, &numSamples_pe, content, material, &aoArgs_pe);
}

void IsoMesher_CalculateMaterials(void * mesh, Vector3I numSamples, void * content, void * material)
{
    ensure_thread_info();
    alignas(16) Vector3I numSamples_pe = numSamples;
    pIsoMesher_CalculateMaterials(mesh, &numSamples_pe, content, material);
}

void IsoMesher_CalculateNormals(void * mesh)
{
    ensure_thread_info();
    pIsoMesher_CalculateNormals(mesh);
}

void RegisterAssertionCallback(void * call)
{
    ensure_thread_info();
    sysv_assertion_callback = call;
    pRegisterAssertionCallback(reinterpret_cast<void *>(&assertion_bridge));
}

void UnregisterAssertionCallback(void)
{
    sysv_assertion_callback = nullptr;
}

void * VrDecimatePostprocessing_Create(void)
{
    ensure_thread_info();
    return pVrDecimatePostprocessing_Create();
}

void VrDecimatePostprocessing_GetClassification(void * instance, void * mesh, void * target, int32_t count)
{
    ensure_thread_info();
    pVrDecimatePostprocessing_GetClassification(instance, mesh, target, count);
}

void VrDecimatePostprocessing_GetClassificationDetails(void * instance, int32_t vertex, void * features, void * featureCount, void * loop, void * loopSize, void * characteristicDistance)
{
    ensure_thread_info();
    pVrDecimatePostprocessing_GetClassificationDetails(instance, vertex, features, featureCount, loop, loopSize, characteristicDistance);
}

float VrDecimatePostprocessing_GetEdgeThreshold(void * instance)
{
    ensure_thread_info();
    return pVrDecimatePostprocessing_GetEdgeThreshold(instance);
}

float VrDecimatePostprocessing_GetFeatureAngle(void * instance)
{
    ensure_thread_info();
    return pVrDecimatePostprocessing_GetFeatureAngle(instance);
}

int32_t VrDecimatePostprocessing_GetIgnoreEdges(void * instance)
{
    ensure_thread_info();
    return pVrDecimatePostprocessing_GetIgnoreEdges(instance);
}

uint64_t VrDecimatePostprocessing_GetInMemorySize(void * instance)
{
    ensure_thread_info();
    return pVrDecimatePostprocessing_GetInMemorySize(instance);
}

float VrDecimatePostprocessing_GetPlaneThreshold(void * instance)
{
    ensure_thread_info();
    return pVrDecimatePostprocessing_GetPlaneThreshold(instance);
}

void VrDecimatePostprocessing_Release(void * instance)
{
    ensure_thread_info();
    pVrDecimatePostprocessing_Release(instance);
}

void VrDecimatePostprocessing_SetEdgeThreshold(void * instance, float value)
{
    ensure_thread_info();
    pVrDecimatePostprocessing_SetEdgeThreshold(instance, value);
}

void VrDecimatePostprocessing_SetFeatureAngle(void * instance, float value)
{
    ensure_thread_info();
    pVrDecimatePostprocessing_SetFeatureAngle(instance, value);
}

void VrDecimatePostprocessing_SetIgnoreEdges(void * instance, int32_t value)
{
    ensure_thread_info();
    pVrDecimatePostprocessing_SetIgnoreEdges(instance, value);
}

void VrDecimatePostprocessing_SetPlaneThreshold(void * instance, float value)
{
    ensure_thread_info();
    pVrDecimatePostprocessing_SetPlaneThreshold(instance, value);
}

int32_t VrDecimatePostprocessing_Simplify(void * instance, int32_t vertex)
{
    ensure_thread_info();
    return pVrDecimatePostprocessing_Simplify(instance, vertex);
}

int32_t VrDecimatePostprocessing_TrySimplify(void * instance, int32_t vertex, void * triangles, void * triangleCount, void * normal)
{
    ensure_thread_info();
    return pVrDecimatePostprocessing_TrySimplify(instance, vertex, triangles, triangleCount, normal);
}

int32_t VrPlanetShape_CheckContentRange(void * instance, Vector3I start, Vector3I end, float lodVoxelSize, int32_t faceHint)
{
    ensure_thread_info();
    alignas(16) Vector3I start_pe = start;
    alignas(16) Vector3I end_pe = end;
    return pVrPlanetShape_CheckContentRange(instance, &start_pe, &end_pe, lodVoxelSize, faceHint);
}

void * VrPlanetShape_Create(Vector3 translation, float radius, float hillMin, float hillMax, MapSet maps, DetailMapData detailMapData, int32_t useLegacyAtan)
{
    ensure_thread_info();
    alignas(16) Vector3 translation_pe = translation;
    alignas(16) MapSet maps_pe = maps;
    alignas(16) DetailMapData detailMapData_pe = detailMapData;
    return pVrPlanetShape_Create(&translation_pe, radius, hillMin, hillMax, &maps_pe, &detailMapData_pe, useLegacyAtan);
}

float VrPlanetShape_GetHeight(void * instance, Vector2 texcoords, int32_t face, void * normal)
{
    ensure_thread_info();
    return pVrPlanetShape_GetHeight(instance, aggregate_bits(texcoords), face, normal);
}

uint64_t VrPlanetShape_GetInMemorySize(void * instance)
{
    ensure_thread_info();
    return pVrPlanetShape_GetInMemorySize(instance);
}

float VrPlanetShape_GetValue(void * instance, Vector2 texcoords, int32_t face, void * normal)
{
    ensure_thread_info();
    return pVrPlanetShape_GetValue(instance, aggregate_bits(texcoords), face, normal);
}

void VrPlanetShape_ReadContentRange(void * instance, void * dest, int32_t destSize, int32_t offset, Vector3I strides, Vector3I start, Vector3I end, float lodVoxelSize, int32_t faceHint)
{
    ensure_thread_info();
    alignas(16) Vector3I strides_pe = strides;
    alignas(16) Vector3I start_pe = start;
    alignas(16) Vector3I end_pe = end;
    pVrPlanetShape_ReadContentRange(instance, dest, destSize, offset, &strides_pe, &start_pe, &end_pe, lodVoxelSize, faceHint);
}

void VrPlanetShape_Release(void * instance)
{
    ensure_thread_info();
    pVrPlanetShape_Release(instance);
}

void VrPostprocessing_Process(void * postprocess, void * mesh)
{
    ensure_thread_info();
    pVrPostprocessing_Process(postprocess, mesh);
}

void * VrRandomizePostprocessing_Create(float ammount)
{
    ensure_thread_info();
    return pVrRandomizePostprocessing_Create(ammount);
}

uint64_t VrRandomizePostprocessing_GetInMemorySize(void * instance)
{
    ensure_thread_info();
    return pVrRandomizePostprocessing_GetInMemorySize(instance);
}

void VrRandomizePostprocessing_Release(void * instance)
{
    ensure_thread_info();
    pVrRandomizePostprocessing_Release(instance);
}

void * VrSewGuide_Create1(int32_t lod, Vector3I min, Vector3I max, void * dataCache)
{
    ensure_thread_info();
    alignas(16) Vector3I min_pe = min;
    alignas(16) Vector3I max_pe = max;
    return pVrSewGuide_Create1(lod, &min_pe, &max_pe, dataCache);
}

void * VrSewGuide_Create2(void * mesh, void * dataCache)
{
    ensure_thread_info();
    return pVrSewGuide_Create2(mesh, dataCache);
}

Vector3I VrSewGuide_GetEnd(void * instance)
{
    ensure_thread_info();
    alignas(16) Vector3I result;
    pVrSewGuide_GetEnd(&result, instance);
    return result;
}

uint64_t VrSewGuide_GetInMemorySize(void * instance)
{
    ensure_thread_info();
    return pVrSewGuide_GetInMemorySize(instance);
}

int32_t VrSewGuide_GetLod(void * instance)
{
    ensure_thread_info();
    return pVrSewGuide_GetLod(instance);
}

void * VrSewGuide_GetMesh(void * instance)
{
    ensure_thread_info();
    return pVrSewGuide_GetMesh(instance);
}

float VrSewGuide_GetScale(void * instance)
{
    ensure_thread_info();
    return pVrSewGuide_GetScale(instance);
}

int32_t VrSewGuide_GetSewn(void * instance)
{
    ensure_thread_info();
    return pVrSewGuide_GetSewn(instance);
}

Vector3I VrSewGuide_GetSize(void * instance)
{
    ensure_thread_info();
    alignas(16) Vector3I result;
    pVrSewGuide_GetSize(&result, instance);
    return result;
}

Vector3I VrSewGuide_GetStart(void * instance)
{
    ensure_thread_info();
    alignas(16) Vector3I result;
    pVrSewGuide_GetStart(&result, instance);
    return result;
}

int32_t VrSewGuide_GetVersion(void * instance)
{
    ensure_thread_info();
    return pVrSewGuide_GetVersion(instance);
}

void VrSewGuide_InvalidateGenerated(void * instance, Vector3I minRange)
{
    ensure_thread_info();
    alignas(16) Vector3I minRange_pe = minRange;
    pVrSewGuide_InvalidateGenerated(instance, &minRange_pe);
}

void VrSewGuide_Recycle1(void * instance, int32_t lod, Vector3I min, Vector3I max, void * dataCache)
{
    ensure_thread_info();
    alignas(16) Vector3I min_pe = min;
    alignas(16) Vector3I max_pe = max;
    pVrSewGuide_Recycle1(instance, lod, &min_pe, &max_pe, dataCache);
}

void VrSewGuide_Recycle2(void * instance, void * mesh, void * dataCache)
{
    ensure_thread_info();
    pVrSewGuide_Recycle2(instance, mesh, dataCache);
}

void VrSewGuide_Release(void * instance)
{
    ensure_thread_info();
    pVrSewGuide_Release(instance);
}

void VrSewGuide_Reset(void * instance)
{
    ensure_thread_info();
    pVrSewGuide_Reset(instance);
}

void VrSewGuide_SetMesh(void * instance, void * mesh, void * dataCache)
{
    ensure_thread_info();
    pVrSewGuide_SetMesh(instance, mesh, dataCache);
}

void * VrShellDataCache_Empty(void)
{
    ensure_thread_info();
    return pVrShellDataCache_Empty();
}

void * VrShellDataCache_FromDataCube(Vector3I size, void * content, void * material)
{
    ensure_thread_info();
    alignas(16) Vector3I size_pe = size;
    return pVrShellDataCache_FromDataCube(&size_pe, content, material);
}

void * VrShellDataCache_Full(void)
{
    ensure_thread_info();
    return pVrShellDataCache_Full();
}

uint64_t VrShellDataCache_GetInMemorySize(void * instance)
{
    ensure_thread_info();
    return pVrShellDataCache_GetInMemorySize(instance);
}

void VrShellDataCache_Release(void * instance)
{
    ensure_thread_info();
    pVrShellDataCache_Release(instance);
}

void VrTailor_ClearBuffers(void * instance)
{
    ensure_thread_info();
    pVrTailor_ClearBuffers(instance);
}

void * VrTailor_Create(void)
{
    ensure_thread_info();
    return pVrTailor_Create();
}

void VrTailor_DebugReadGenerated(void * instance, void * generatedVertices, void * count)
{
    ensure_thread_info();
    pVrTailor_DebugReadGenerated(instance, generatedVertices, count);
}

void VrTailor_DebugReadRemapped(void * instance, void * remappedVertices, void * count)
{
    ensure_thread_info();
    pVrTailor_DebugReadRemapped(instance, remappedVertices, count);
}

void VrTailor_DebugReadStudied(void * instance, void * studiedVertices, void * count)
{
    ensure_thread_info();
    pVrTailor_DebugReadStudied(instance, studiedVertices, count);
}

uint64_t VrTailor_GetInMemorySize(void * instance)
{
    ensure_thread_info();
    return pVrTailor_GetInMemorySize(instance);
}

void VrTailor_RecalculateEdgeNormal(void * instance, void * guides)
{
    ensure_thread_info();
    pVrTailor_RecalculateEdgeNormal(instance, guides);
}

void VrTailor_Release(void * instance)
{
    ensure_thread_info();
    pVrTailor_Release(instance);
}

void VrTailor_SetDebug(void * instance, int32_t debug)
{
    ensure_thread_info();
    pVrTailor_SetDebug(instance, debug);
}

void VrTailor_SetGenerate(void * instance, uint8_t generate)
{
    ensure_thread_info();
    pVrTailor_SetGenerate(instance, generate);
}

void VrTailor_Sew(void * instance, void * guides, uint8_t operations, Vector3I min, Vector3I max)
{
    ensure_thread_info();
    alignas(16) Vector3I min_pe = min;
    alignas(16) Vector3I max_pe = max;
    pVrTailor_Sew(instance, guides, operations, &min_pe, &max_pe);
}

void VrVoxelMesh_Clear(void * instance)
{
    ensure_thread_info();
    pVrVoxelMesh_Clear(instance);
}

void * VrVoxelMesh_Create(Vector3I start, Vector3I end, int32_t lod)
{
    ensure_thread_info();
    alignas(16) Vector3I start_pe = start;
    alignas(16) Vector3I end_pe = end;
    return pVrVoxelMesh_Create(&start_pe, &end_pe, lod);
}

Vector3I VrVoxelMesh_GetEnd(void * instance)
{
    ensure_thread_info();
    alignas(16) Vector3I result;
    pVrVoxelMesh_GetEnd(&result, instance);
    return result;
}

uint64_t VrVoxelMesh_GetInMemorySize(void * instance)
{
    ensure_thread_info();
    return pVrVoxelMesh_GetInMemorySize(instance);
}

int32_t VrVoxelMesh_GetLod(void * instance)
{
    ensure_thread_info();
    return pVrVoxelMesh_GetLod(instance);
}

void VrVoxelMesh_GetMeshData(void * instance, void * positions, void * normals, void * materials, void * cells, void * color, void * triangles)
{
    ensure_thread_info();
    pVrVoxelMesh_GetMeshData(instance, positions, normals, materials, cells, color, triangles);
}

float VrVoxelMesh_GetScale(void * instance)
{
    ensure_thread_info();
    return pVrVoxelMesh_GetScale(instance);
}

Vector3I VrVoxelMesh_GetStart(void * instance)
{
    ensure_thread_info();
    alignas(16) Vector3I result;
    pVrVoxelMesh_GetStart(&result, instance);
    return result;
}

int32_t VrVoxelMesh_GetTriangleCount(void * instance)
{
    ensure_thread_info();
    return pVrVoxelMesh_GetTriangleCount(instance);
}

void * VrVoxelMesh_GetTriangles(void * instance)
{
    ensure_thread_info();
    return pVrVoxelMesh_GetTriangles(instance);
}

int32_t VrVoxelMesh_GetVertexCount(void * instance)
{
    ensure_thread_info();
    return pVrVoxelMesh_GetVertexCount(instance);
}

void * VrVoxelMesh_GetVertices(void * instance)
{
    ensure_thread_info();
    return pVrVoxelMesh_GetVertices(instance);
}

void VrVoxelMesh_Recycle(void * instance, Vector3I start, Vector3I end, int32_t lod)
{
    ensure_thread_info();
    alignas(16) Vector3I start_pe = start;
    alignas(16) Vector3I end_pe = end;
    pVrVoxelMesh_Recycle(instance, &start_pe, &end_pe, lod);
}

void VrVoxelMesh_Release(void * instance)
{
    ensure_thread_info();
    pVrVoxelMesh_Release(instance);
}

}
