// Generated by tools/generate_voxels_wrapper.py. Do not edit.
#include <cstdint>
#include <cstdlib>
#include <mutex>
#include <stdexcept>
#include <string>

#include "dll_loader.h"

struct Vector3I {
    int32_t x, y, z;
};

struct AmbientOcclusionArgs {
    float values[7];
};

static_assert(sizeof(Vector3I) == 12);
static_assert(sizeof(AmbientOcclusionArgs) == 28);

namespace {
pe_image voxels_image;
std::once_flag voxels_once;
std::string voxels_path;
thread_local bool voxels_thread_ready;
void *sysv_assertion_callback;

void WINAPI assertion_bridge(const char *message)
{
    if (sysv_assertion_callback)
        reinterpret_cast<void (*)(const char *)>(sysv_assertion_callback)(message);
}

void initialize(const char *dll_path, const char *sidecar_path);

void ensure_thread_info()
{
    initialize(nullptr, nullptr);
    if (voxels_thread_ready)
        return;
    if (!setup_nt_threadinfo(nullptr))
        std::abort();
    pe_ensure_tls_for_loaded_images();
    voxels_thread_ready = true;
}

using IsoMesher_Calculate_t = void(WINAPI *)(void *, Vector3I *, void *, void *, AmbientOcclusionArgs *);
IsoMesher_Calculate_t pIsoMesher_Calculate;
using IsoMesher_CalculateNormals_t = void(WINAPI *)(void *);
IsoMesher_CalculateNormals_t pIsoMesher_CalculateNormals;
using RegisterAssertionCallback_t = void(WINAPI *)(void *);
RegisterAssertionCallback_t pRegisterAssertionCallback;
using VrSewGuide_Create1_t = void *(WINAPI *)(int32_t, Vector3I *, Vector3I *, void *);
VrSewGuide_Create1_t pVrSewGuide_Create1;
using VrSewGuide_Create2_t = void *(WINAPI *)(void *, void *);
VrSewGuide_Create2_t pVrSewGuide_Create2;
using VrSewGuide_GetEnd_t = void(WINAPI *)(Vector3I *, void *);
VrSewGuide_GetEnd_t pVrSewGuide_GetEnd;
using VrSewGuide_GetInMemorySize_t = int64_t(WINAPI *)(void *);
VrSewGuide_GetInMemorySize_t pVrSewGuide_GetInMemorySize;
using VrSewGuide_GetLod_t = int32_t(WINAPI *)(void *);
VrSewGuide_GetLod_t pVrSewGuide_GetLod;
using VrSewGuide_GetMesh_t = void *(WINAPI *)(void *);
VrSewGuide_GetMesh_t pVrSewGuide_GetMesh;
using VrSewGuide_GetSewn_t = int32_t(WINAPI *)(void *);
VrSewGuide_GetSewn_t pVrSewGuide_GetSewn;
using VrSewGuide_GetSize_t = void(WINAPI *)(Vector3I *, void *);
VrSewGuide_GetSize_t pVrSewGuide_GetSize;
using VrSewGuide_GetStart_t = void(WINAPI *)(Vector3I *, void *);
VrSewGuide_GetStart_t pVrSewGuide_GetStart;
using VrSewGuide_GetVersion_t = int32_t(WINAPI *)(void *);
VrSewGuide_GetVersion_t pVrSewGuide_GetVersion;
using VrSewGuide_InvalidateGenerated_t = void(WINAPI *)(void *, Vector3I *);
VrSewGuide_InvalidateGenerated_t pVrSewGuide_InvalidateGenerated;
using VrSewGuide_SetMesh_t = void(WINAPI *)(void *, void *, void *);
VrSewGuide_SetMesh_t pVrSewGuide_SetMesh;
using VrSewGuide_Release_t = void(WINAPI *)(void *);
VrSewGuide_Release_t pVrSewGuide_Release;
using VrSewGuide_Reset_t = void(WINAPI *)(void *);
VrSewGuide_Reset_t pVrSewGuide_Reset;
using VrShellDataCache_Empty_t = void *(WINAPI *)(void);
VrShellDataCache_Empty_t pVrShellDataCache_Empty;
using VrShellDataCache_FromDataCube_t = void *(WINAPI *)(Vector3I *, void *, void *);
VrShellDataCache_FromDataCube_t pVrShellDataCache_FromDataCube;
using VrShellDataCache_Full_t = void *(WINAPI *)(void);
VrShellDataCache_Full_t pVrShellDataCache_Full;
using VrShellDataCache_GetInMemorySize_t = int64_t(WINAPI *)(void *);
VrShellDataCache_GetInMemorySize_t pVrShellDataCache_GetInMemorySize;
using VrShellDataCache_Release_t = void(WINAPI *)(void *);
VrShellDataCache_Release_t pVrShellDataCache_Release;
using VrTailor_Create_t = void *(WINAPI *)(void);
VrTailor_Create_t pVrTailor_Create;
using VrTailor_GetInMemorySize_t = int64_t(WINAPI *)(void *);
VrTailor_GetInMemorySize_t pVrTailor_GetInMemorySize;
using VrTailor_RecalculateEdgeNormal_t = void(WINAPI *)(void *, void *);
VrTailor_RecalculateEdgeNormal_t pVrTailor_RecalculateEdgeNormal;
using VrTailor_SetDebug_t = void(WINAPI *)(void *, int32_t);
VrTailor_SetDebug_t pVrTailor_SetDebug;
using VrTailor_SetGenerate_t = void(WINAPI *)(void *, uint8_t);
VrTailor_SetGenerate_t pVrTailor_SetGenerate;
using VrTailor_Sew_t = void(WINAPI *)(void *, void *, uint8_t, Vector3I *, Vector3I *);
VrTailor_Sew_t pVrTailor_Sew;
using VrVoxelMesh_Create_t = void *(WINAPI *)(Vector3I *, Vector3I *, int32_t);
VrVoxelMesh_Create_t pVrVoxelMesh_Create;
using VrVoxelMesh_Clear_t = void(WINAPI *)(void *);
VrVoxelMesh_Clear_t pVrVoxelMesh_Clear;
using VrVoxelMesh_GetInMemorySize_t = int64_t(WINAPI *)(void *);
VrVoxelMesh_GetInMemorySize_t pVrVoxelMesh_GetInMemorySize;
using VrVoxelMesh_GetTriangleCount_t = int32_t(WINAPI *)(void *);
VrVoxelMesh_GetTriangleCount_t pVrVoxelMesh_GetTriangleCount;
using VrVoxelMesh_GetTriangles_t = void *(WINAPI *)(void *);
VrVoxelMesh_GetTriangles_t pVrVoxelMesh_GetTriangles;
using VrVoxelMesh_GetVertexCount_t = int32_t(WINAPI *)(void *);
VrVoxelMesh_GetVertexCount_t pVrVoxelMesh_GetVertexCount;
using VrVoxelMesh_GetVertices_t = void *(WINAPI *)(void *);
VrVoxelMesh_GetVertices_t pVrVoxelMesh_GetVertices;
using VrVoxelMesh_Release_t = void(WINAPI *)(void *);
VrVoxelMesh_Release_t pVrVoxelMesh_Release;

void initialize(const char *dll_path, const char *sidecar_path)
{
    std::call_once(voxels_once, [dll_path, sidecar_path] {
        if (dll_path) {
            voxels_path = dll_path;
        } else {
            // Playback loads exports directly; deployed wrappers receive the path through Init.
            const char *home = std::getenv("HOME");
            if (!home)
                throw std::runtime_error("HOME is not set; call Init with the Voxels DLL path");
            voxels_path = std::string(home) + "/Documents/Se2-Game2/VRage.Voxels.Native.dll";
        }

        if (!load_dll(&voxels_image, voxels_path.c_str(), sidecar_path))
            throw std::runtime_error("Failed to load VRage.Voxels.Native.dll");
        pIsoMesher_Calculate = reinterpret_cast<IsoMesher_Calculate_t>(get_export("IsoMesher_Calculate"));
        if (!pIsoMesher_Calculate)
            throw std::runtime_error("Missing Voxels export: IsoMesher_Calculate");
        pIsoMesher_CalculateNormals = reinterpret_cast<IsoMesher_CalculateNormals_t>(get_export("IsoMesher_CalculateNormals"));
        if (!pIsoMesher_CalculateNormals)
            throw std::runtime_error("Missing Voxels export: IsoMesher_CalculateNormals");
        pRegisterAssertionCallback = reinterpret_cast<RegisterAssertionCallback_t>(get_export("RegisterAssertionCallback"));
        if (!pRegisterAssertionCallback)
            throw std::runtime_error("Missing Voxels export: RegisterAssertionCallback");
        pVrSewGuide_Create1 = reinterpret_cast<VrSewGuide_Create1_t>(get_export("VrSewGuide_Create1"));
        if (!pVrSewGuide_Create1)
            throw std::runtime_error("Missing Voxels export: VrSewGuide_Create1");
        pVrSewGuide_Create2 = reinterpret_cast<VrSewGuide_Create2_t>(get_export("VrSewGuide_Create2"));
        if (!pVrSewGuide_Create2)
            throw std::runtime_error("Missing Voxels export: VrSewGuide_Create2");
        pVrSewGuide_GetEnd = reinterpret_cast<VrSewGuide_GetEnd_t>(get_export("VrSewGuide_GetEnd"));
        if (!pVrSewGuide_GetEnd)
            throw std::runtime_error("Missing Voxels export: VrSewGuide_GetEnd");
        pVrSewGuide_GetInMemorySize = reinterpret_cast<VrSewGuide_GetInMemorySize_t>(get_export("VrSewGuide_GetInMemorySize"));
        if (!pVrSewGuide_GetInMemorySize)
            throw std::runtime_error("Missing Voxels export: VrSewGuide_GetInMemorySize");
        pVrSewGuide_GetLod = reinterpret_cast<VrSewGuide_GetLod_t>(get_export("VrSewGuide_GetLod"));
        if (!pVrSewGuide_GetLod)
            throw std::runtime_error("Missing Voxels export: VrSewGuide_GetLod");
        pVrSewGuide_GetMesh = reinterpret_cast<VrSewGuide_GetMesh_t>(get_export("VrSewGuide_GetMesh"));
        if (!pVrSewGuide_GetMesh)
            throw std::runtime_error("Missing Voxels export: VrSewGuide_GetMesh");
        pVrSewGuide_GetSewn = reinterpret_cast<VrSewGuide_GetSewn_t>(get_export("VrSewGuide_GetSewn"));
        if (!pVrSewGuide_GetSewn)
            throw std::runtime_error("Missing Voxels export: VrSewGuide_GetSewn");
        pVrSewGuide_GetSize = reinterpret_cast<VrSewGuide_GetSize_t>(get_export("VrSewGuide_GetSize"));
        if (!pVrSewGuide_GetSize)
            throw std::runtime_error("Missing Voxels export: VrSewGuide_GetSize");
        pVrSewGuide_GetStart = reinterpret_cast<VrSewGuide_GetStart_t>(get_export("VrSewGuide_GetStart"));
        if (!pVrSewGuide_GetStart)
            throw std::runtime_error("Missing Voxels export: VrSewGuide_GetStart");
        pVrSewGuide_GetVersion = reinterpret_cast<VrSewGuide_GetVersion_t>(get_export("VrSewGuide_GetVersion"));
        if (!pVrSewGuide_GetVersion)
            throw std::runtime_error("Missing Voxels export: VrSewGuide_GetVersion");
        pVrSewGuide_InvalidateGenerated = reinterpret_cast<VrSewGuide_InvalidateGenerated_t>(get_export("VrSewGuide_InvalidateGenerated"));
        if (!pVrSewGuide_InvalidateGenerated)
            throw std::runtime_error("Missing Voxels export: VrSewGuide_InvalidateGenerated");
        pVrSewGuide_SetMesh = reinterpret_cast<VrSewGuide_SetMesh_t>(get_export("VrSewGuide_SetMesh"));
        if (!pVrSewGuide_SetMesh)
            throw std::runtime_error("Missing Voxels export: VrSewGuide_SetMesh");
        pVrSewGuide_Release = reinterpret_cast<VrSewGuide_Release_t>(get_export("VrSewGuide_Release"));
        if (!pVrSewGuide_Release)
            throw std::runtime_error("Missing Voxels export: VrSewGuide_Release");
        pVrSewGuide_Reset = reinterpret_cast<VrSewGuide_Reset_t>(get_export("VrSewGuide_Reset"));
        if (!pVrSewGuide_Reset)
            throw std::runtime_error("Missing Voxels export: VrSewGuide_Reset");
        pVrShellDataCache_Empty = reinterpret_cast<VrShellDataCache_Empty_t>(get_export("VrShellDataCache_Empty"));
        if (!pVrShellDataCache_Empty)
            throw std::runtime_error("Missing Voxels export: VrShellDataCache_Empty");
        pVrShellDataCache_FromDataCube = reinterpret_cast<VrShellDataCache_FromDataCube_t>(get_export("VrShellDataCache_FromDataCube"));
        if (!pVrShellDataCache_FromDataCube)
            throw std::runtime_error("Missing Voxels export: VrShellDataCache_FromDataCube");
        pVrShellDataCache_Full = reinterpret_cast<VrShellDataCache_Full_t>(get_export("VrShellDataCache_Full"));
        if (!pVrShellDataCache_Full)
            throw std::runtime_error("Missing Voxels export: VrShellDataCache_Full");
        pVrShellDataCache_GetInMemorySize = reinterpret_cast<VrShellDataCache_GetInMemorySize_t>(get_export("VrShellDataCache_GetInMemorySize"));
        if (!pVrShellDataCache_GetInMemorySize)
            throw std::runtime_error("Missing Voxels export: VrShellDataCache_GetInMemorySize");
        pVrShellDataCache_Release = reinterpret_cast<VrShellDataCache_Release_t>(get_export("VrShellDataCache_Release"));
        if (!pVrShellDataCache_Release)
            throw std::runtime_error("Missing Voxels export: VrShellDataCache_Release");
        pVrTailor_Create = reinterpret_cast<VrTailor_Create_t>(get_export("VrTailor_Create"));
        if (!pVrTailor_Create)
            throw std::runtime_error("Missing Voxels export: VrTailor_Create");
        pVrTailor_GetInMemorySize = reinterpret_cast<VrTailor_GetInMemorySize_t>(get_export("VrTailor_GetInMemorySize"));
        if (!pVrTailor_GetInMemorySize)
            throw std::runtime_error("Missing Voxels export: VrTailor_GetInMemorySize");
        pVrTailor_RecalculateEdgeNormal = reinterpret_cast<VrTailor_RecalculateEdgeNormal_t>(get_export("VrTailor_RecalculateEdgeNormal"));
        if (!pVrTailor_RecalculateEdgeNormal)
            throw std::runtime_error("Missing Voxels export: VrTailor_RecalculateEdgeNormal");
        pVrTailor_SetDebug = reinterpret_cast<VrTailor_SetDebug_t>(get_export("VrTailor_SetDebug"));
        if (!pVrTailor_SetDebug)
            throw std::runtime_error("Missing Voxels export: VrTailor_SetDebug");
        pVrTailor_SetGenerate = reinterpret_cast<VrTailor_SetGenerate_t>(get_export("VrTailor_SetGenerate"));
        if (!pVrTailor_SetGenerate)
            throw std::runtime_error("Missing Voxels export: VrTailor_SetGenerate");
        pVrTailor_Sew = reinterpret_cast<VrTailor_Sew_t>(get_export("VrTailor_Sew"));
        if (!pVrTailor_Sew)
            throw std::runtime_error("Missing Voxels export: VrTailor_Sew");
        pVrVoxelMesh_Create = reinterpret_cast<VrVoxelMesh_Create_t>(get_export("VrVoxelMesh_Create"));
        if (!pVrVoxelMesh_Create)
            throw std::runtime_error("Missing Voxels export: VrVoxelMesh_Create");
        pVrVoxelMesh_Clear = reinterpret_cast<VrVoxelMesh_Clear_t>(get_export("VrVoxelMesh_Clear"));
        if (!pVrVoxelMesh_Clear)
            throw std::runtime_error("Missing Voxels export: VrVoxelMesh_Clear");
        pVrVoxelMesh_GetInMemorySize = reinterpret_cast<VrVoxelMesh_GetInMemorySize_t>(get_export("VrVoxelMesh_GetInMemorySize"));
        if (!pVrVoxelMesh_GetInMemorySize)
            throw std::runtime_error("Missing Voxels export: VrVoxelMesh_GetInMemorySize");
        pVrVoxelMesh_GetTriangleCount = reinterpret_cast<VrVoxelMesh_GetTriangleCount_t>(get_export("VrVoxelMesh_GetTriangleCount"));
        if (!pVrVoxelMesh_GetTriangleCount)
            throw std::runtime_error("Missing Voxels export: VrVoxelMesh_GetTriangleCount");
        pVrVoxelMesh_GetTriangles = reinterpret_cast<VrVoxelMesh_GetTriangles_t>(get_export("VrVoxelMesh_GetTriangles"));
        if (!pVrVoxelMesh_GetTriangles)
            throw std::runtime_error("Missing Voxels export: VrVoxelMesh_GetTriangles");
        pVrVoxelMesh_GetVertexCount = reinterpret_cast<VrVoxelMesh_GetVertexCount_t>(get_export("VrVoxelMesh_GetVertexCount"));
        if (!pVrVoxelMesh_GetVertexCount)
            throw std::runtime_error("Missing Voxels export: VrVoxelMesh_GetVertexCount");
        pVrVoxelMesh_GetVertices = reinterpret_cast<VrVoxelMesh_GetVertices_t>(get_export("VrVoxelMesh_GetVertices"));
        if (!pVrVoxelMesh_GetVertices)
            throw std::runtime_error("Missing Voxels export: VrVoxelMesh_GetVertices");
        pVrVoxelMesh_Release = reinterpret_cast<VrVoxelMesh_Release_t>(get_export("VrVoxelMesh_Release"));
        if (!pVrVoxelMesh_Release)
            throw std::runtime_error("Missing Voxels export: VrVoxelMesh_Release");
    });
}
}

extern "C" {

void Init(const char *dll_path, const char *sidecar_path)
{
    initialize(dll_path, sidecar_path);
}

void IsoMesher_Calculate(void * mesh, Vector3I numSamples, void * content, void * material, AmbientOcclusionArgs aoArgs)
{
    ensure_thread_info();
    pIsoMesher_Calculate(mesh, &numSamples, content, material, &aoArgs);
}

void IsoMesher_CalculateNormals(void * mesh)
{
    ensure_thread_info();
    pIsoMesher_CalculateNormals(mesh);
}

void RegisterAssertionCallback(void * call)
{
    ensure_thread_info();
    sysv_assertion_callback = call;
    pRegisterAssertionCallback(reinterpret_cast<void *>(&assertion_bridge));
}

void * VrSewGuide_Create1(int32_t lod, Vector3I min, Vector3I max, void * dataCache)
{
    ensure_thread_info();
    return pVrSewGuide_Create1(lod, &min, &max, dataCache);
}

void * VrSewGuide_Create2(void * mesh, void * dataCache)
{
    ensure_thread_info();
    return pVrSewGuide_Create2(mesh, dataCache);
}

Vector3I VrSewGuide_GetEnd(void * instance)
{
    ensure_thread_info();
    Vector3I result;
    pVrSewGuide_GetEnd(&result, instance);
    return result;
}

int64_t VrSewGuide_GetInMemorySize(void * instance)
{
    ensure_thread_info();
    return pVrSewGuide_GetInMemorySize(instance);
}

int32_t VrSewGuide_GetLod(void * instance)
{
    ensure_thread_info();
    return pVrSewGuide_GetLod(instance);
}

void * VrSewGuide_GetMesh(void * instance)
{
    ensure_thread_info();
    return pVrSewGuide_GetMesh(instance);
}

int32_t VrSewGuide_GetSewn(void * instance)
{
    ensure_thread_info();
    return pVrSewGuide_GetSewn(instance);
}

Vector3I VrSewGuide_GetSize(void * instance)
{
    ensure_thread_info();
    Vector3I result;
    pVrSewGuide_GetSize(&result, instance);
    return result;
}

Vector3I VrSewGuide_GetStart(void * instance)
{
    ensure_thread_info();
    Vector3I result;
    pVrSewGuide_GetStart(&result, instance);
    return result;
}

int32_t VrSewGuide_GetVersion(void * instance)
{
    ensure_thread_info();
    return pVrSewGuide_GetVersion(instance);
}

void VrSewGuide_InvalidateGenerated(void * instance, Vector3I minRange)
{
    ensure_thread_info();
    pVrSewGuide_InvalidateGenerated(instance, &minRange);
}

void VrSewGuide_SetMesh(void * instance, void * mesh, void * dataCache)
{
    ensure_thread_info();
    pVrSewGuide_SetMesh(instance, mesh, dataCache);
}

void VrSewGuide_Release(void * instance)
{
    ensure_thread_info();
    pVrSewGuide_Release(instance);
}

void VrSewGuide_Reset(void * instance)
{
    ensure_thread_info();
    pVrSewGuide_Reset(instance);
}

void * VrShellDataCache_Empty(void)
{
    ensure_thread_info();
    return pVrShellDataCache_Empty();
}

void * VrShellDataCache_FromDataCube(Vector3I size, void * content, void * material)
{
    ensure_thread_info();
    return pVrShellDataCache_FromDataCube(&size, content, material);
}

void * VrShellDataCache_Full(void)
{
    ensure_thread_info();
    return pVrShellDataCache_Full();
}

int64_t VrShellDataCache_GetInMemorySize(void * instance)
{
    ensure_thread_info();
    return pVrShellDataCache_GetInMemorySize(instance);
}

void VrShellDataCache_Release(void * instance)
{
    ensure_thread_info();
    pVrShellDataCache_Release(instance);
}

void * VrTailor_Create(void)
{
    ensure_thread_info();
    return pVrTailor_Create();
}

int64_t VrTailor_GetInMemorySize(void * instance)
{
    ensure_thread_info();
    return pVrTailor_GetInMemorySize(instance);
}

void VrTailor_RecalculateEdgeNormal(void * instance, void * guides)
{
    ensure_thread_info();
    pVrTailor_RecalculateEdgeNormal(instance, guides);
}

void VrTailor_SetDebug(void * instance, int32_t debug)
{
    ensure_thread_info();
    pVrTailor_SetDebug(instance, debug);
}

void VrTailor_SetGenerate(void * instance, uint8_t generate)
{
    ensure_thread_info();
    pVrTailor_SetGenerate(instance, generate);
}

void VrTailor_Sew(void * instance, void * guides, uint8_t operations, Vector3I min, Vector3I max)
{
    ensure_thread_info();
    pVrTailor_Sew(instance, guides, operations, &min, &max);
}

void * VrVoxelMesh_Create(Vector3I start, Vector3I end, int32_t lod)
{
    ensure_thread_info();
    return pVrVoxelMesh_Create(&start, &end, lod);
}

void VrVoxelMesh_Clear(void * instance)
{
    ensure_thread_info();
    pVrVoxelMesh_Clear(instance);
}

int64_t VrVoxelMesh_GetInMemorySize(void * instance)
{
    ensure_thread_info();
    return pVrVoxelMesh_GetInMemorySize(instance);
}

int32_t VrVoxelMesh_GetTriangleCount(void * instance)
{
    ensure_thread_info();
    return pVrVoxelMesh_GetTriangleCount(instance);
}

void * VrVoxelMesh_GetTriangles(void * instance)
{
    ensure_thread_info();
    return pVrVoxelMesh_GetTriangles(instance);
}

int32_t VrVoxelMesh_GetVertexCount(void * instance)
{
    ensure_thread_info();
    return pVrVoxelMesh_GetVertexCount(instance);
}

void * VrVoxelMesh_GetVertices(void * instance)
{
    ensure_thread_info();
    return pVrVoxelMesh_GetVertices(instance);
}

void VrVoxelMesh_Release(void * instance)
{
    ensure_thread_info();
    pVrVoxelMesh_Release(instance);
}

void UnregisterAssertionCallback(void)
{
}

}
